function l(b,a,c,d){b.i.ma(b.S,a,c,d)}function m(b,a,c,d){b.i.o?l(b,a,c,d):b.i.qb()._OnMessageFromDOM({type:"event",component:b.S,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.i.g(b.S,a,c)}function ba(b,a){for(const [c,d]of a)aa(b,c,d)}window.Ia=class{constructor(b,a){this.i=b;this.S=a}Ga(){}};window.Vb=class{constructor(){}};"use strict";class ca{constructor(b){this.ta=b;this.va=!1;this.ya=!0}}
function da(b,a){const c=a.elementId,d=b.H(c,a),e=new ca(d);b.T.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.ya=!!a.isVisible;a=b.oa(d);a.addEventListener("focus",()=>{q(b,"elem-focused",c)});a.addEventListener("blur",()=>{q(b,"elem-blurred",c)});b.ca&&document.body.appendChild(d)}function r(b,a,c){aa(b,a,d=>{const e=t(b,d.elementId);return c(e,d)})}function t(b,a){b=b.T.get(a);if(!b)throw Error(`no element with id ${a}`);return b.ta}
function q(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}function u(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}
window.O=class extends self.Ia{constructor(b,a){super(b,a);this.T=new Map;this.ca=!0;ba(this,[["create",c=>da(this,c)],["destroy",c=>{c=c.elementId;const d=t(this,c);this.Ja(d);this.ca&&d.parentElement.removeChild(d);this.T.delete(c)}],["set-visible",c=>{if(this.ca){var d=this.T.get(c.elementId),e=d.ta;d.va?e.style.display=c.isVisible?"":"none":d.ya=!!c.isVisible}}],["update-position",c=>{if(this.ca){var d=this.T.get(c.elementId),e=d.ta;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.va||(d.va=!0,d.ya&&(e.style.display=""))}}],["update-state",c=>{const d=t(this,c.elementId);this.u(d,c)}],["focus",c=>{const d=this.oa(t(this,c.elementId));c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=t(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{t(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{t(this,
c.elementId).removeAttribute(c.name)}]]);r(this,"get-element",c=>c)}H(){throw Error("required override");}Ja(){}u(){throw Error("required override");}oa(b){return b}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ha=0;
function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Lb?new Promise(c=>{const d="c3_resolve_"+ha;++ha;self[d]=c;a.textContent=b.Pb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ia=!1,ja=!1;function ka(){if(!ia){try{new Worker("blob://",{get type(){ja=!0}})}catch(b){}ia=!0}return ja}let x=new Audio;
const la={"audio/webm; codecs=opus":!!x.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!x.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!x.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!x.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!x.canPlayType("audio/mp4"),"audio/mpeg":!!x.canPlayType("audio/mpeg")};x=null;async function ma(b){b=await na(b);return(new TextDecoder("utf-8")).decode(b)}
function na(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const y=[];let z=0;window.RealFile=window.File;const A=[],B=new Map,C=new Map;let oa=0;const pa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");pa.push(b)};const qa=new Set(["cordova","playable-ad","instant-games"]);let ra=!1;
window.D=class b{constructor(a){this.o=a.Rb;this.W=null;this.m="";this.K=a.Ob;this.$={};this.Aa=this.M=null;this.da=[];this.j=this.Y=null;this.Wa=!1;this.U=null;this.J=-1;this.Gb=()=>this.xb();this.Da=[];this.h=a.Za;this.xa="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ka()||(this.o=!1);this.o&&fa&&(this.o=!1);if("playable-ad"===this.h||"instant-games"===this.h)this.o=!1;if("cordova"===this.h&&this.o)if(v){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.o=!1)}else this.o=!1;this.fa=this.B=null;"html5"!==this.h||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.g("runtime","cordova-fetch-local-file",c=>this.tb(c));this.g("runtime","create-job-worker",()=>this.ub());"cordova"===this.h?document.addEventListener("deviceready",()=>this.Na(a)):this.Na(a)}eb(){return ea&&
"cordova"===this.h}la(){const a=navigator.userAgent;return ea&&qa.has(this.h)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}bb(){return v}Ka(){return v&&qa.has(this.h)}async Na(a){"macos-wkwebview"===this.h&&this.Bb();if("playable-ad"===this.h){this.B=self.c3_base64files;this.fa={};await this.mb();for(let d=0,e=a.N.length;d<e;++d){var c=a.N[d];this.fa.hasOwnProperty(c)?a.N[d]={Lb:!0,Pb:this.fa[c]}:this.B.hasOwnProperty(c)&&(a.N[d]=URL.createObjectURL(this.B[c]))}a.ia=[]}if("nwjs"===this.h&&
self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.ib(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Nb?this.m=a.Nb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.Tb&&(this.$=a.Tb);c=new MessageChannel;this.W=c.port1;this.W.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.wb(d));this.U=new self.fb(this);await sa(this.U);
"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.o?await this.sb(a,c.port2):await this.rb(a,c.port2)}pa(a){a=this.$.hasOwnProperty(a)?this.$[a]:a.endsWith("/workermain.js")&&this.$.hasOwnProperty("workermain.js")?this.$["workermain.js"]:"playable-ad"===this.h&&this.B.hasOwnProperty(a)?this.B[a]:
a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ka(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.h&&this.xa)return a=await this.ja(d.Kb?a:this.K+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}A(){return Math.max(window.innerWidth,
1)}v(){return Math.max(window.innerHeight,1)}Ma(a){var c=this.m,d=location.href,e=this.A(),f=this.v(),g=window.devicePixelRatio,h=b.P(),k=a.Zb,n=window.cr_previewImageBlobs||this.B,p=window.cr_previewProjectFileBlobs,Ha=window.cr_previewProjectFiles,Ja=window.Xb||"";a=a.Za;var Ka=(new URLSearchParams(self.location.search)).has("debug"),Q=this.U;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:n,previewProjectFileBlobs:p,
previewProjectFileSWUrls:Ha,swClientId:Ja,exportType:a,isDebug:Ka,ife:!!self.Yb,jobScheduler:{inputPort:Q.wa,outputPort:Q.Ca,maxNumWorkers:Q.Eb},supportedAudioFormats:la,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.K+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.K+"opus.wasm.wasm",isFileProtocol:this.xa,isiOSCordova:this.eb(),isiOSWebView:this.la(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async sb(a,c){const d=this.pa(a.Sb);"preview"===this.h?(this.M=new Worker("previewworker.js",
{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const n=p=>{this.M.removeEventListener("message",n);p.data&&"ok"===p.data.type?h():k()};this.M.addEventListener("message",n);this.M.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.M=await this.ka(d,this.m,{type:"module",name:"Runtime",Kb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=
this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ia||[],g=a.N;f=await Promise.all(f.map(h=>this.I(h)));g=await Promise.all(g.map(h=>this.I(h)));if("cordova"===this.h)for(let h=0,k=a.ha.length;h<k;++h){const n=a.ha[h],p=n[0];if(p===a.Fa||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n[1]=await this.I(p)}this.M.postMessage(Object.assign(this.Ma(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ha,
mainProjectScript:a.Fa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ta(this.U)]);this.da=A.map(h=>new h(this));this.La();ua(this.Y);self.c3_callFunction=(h,k)=>{var n=this.Y;return n.i.gb(n.S,{name:h,params:k})};"preview"===this.h&&(self.goToLastErrorScript=()=>this.ma("runtime","go-to-last-error-script"))}async rb(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
this.da=A.map(g=>new g(this));this.La();var d=a.N.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);if(Array.isArray(a.ia)){var e=[...a.ia].map(g=>g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.I(g)));await Promise.all(d.map(g=>w(g)));d=self.C3_ProjectScriptsStatus;e=a.Fa;const f=a.ha;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.I(h),await w(h),"preview"!==this.h||d[g]||this.Pa(g,"main script did not run to completion")}catch(k){this.Pa(g,
k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.I(h),await w(h);"preview"===this.h&&"object"!==typeof self.Ub.Wb?(this.ba(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ma(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:pa}),ua(this.Y),
this.Oa(),this.Aa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Aa,a))}Pa(a,c){this.ba();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Oa(){this.ba()}ba(){const a=window.Ib;a&&(a.parentElement.removeChild(a),window.Ib=null)}async ub(){const a=await va(this.U);return{outputPort:a,transferables:[a]}}qb(){if(this.o)throw Error("not available in worker mode");
return this.Aa}ma(a,c,d,e){this.W.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},void 0)}gb(a,c){const d=oa++,e=new Promise((f,g)=>{C.set(d,{resolve:f,reject:g})});this.W.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.vb(a);if("result"===c)this.yb(a);else if("runtime-ready"===c)this.zb();else if("alert-error"===
c)this.ba(),alert(a.message);else if("creating-runtime"===c)this.Oa();else throw Error(`unknown message '${c}'`);}vb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=B.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.aa(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.aa(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.aa(f,!1,""+h)}):this.aa(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);
else console.warn(`[DOM] No event handlers for component '${c}'`)}aa(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.W.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}yb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=C.get(c);d?e.resolve(a):e.reject(a);C.delete(c)}g(a,c,d){let e=B.get(a);e||(e=new Map,B.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static G(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}La(){for(const a of this.da)if("runtime"===
a.S){this.Y=a;return}throw Error("cannot find runtime DOM handler");}wb(a){this.ma("debugger","message",a)}zb(){for(const a of this.da)a.Ga()}static P(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ra)}static Qa(a){ra=!!a}ib(a){this.Da.push(a);this.ra()}ra(){-1===this.J&&this.Da.length&&(this.J=requestAnimationFrame(this.Gb))}kb(){-1!==this.J&&(cancelAnimationFrame(this.J),this.J=-1)}xb(){this.J=-1;for(const a of this.Da)a();this.ra()}qa(){this.Y.qa()}hb(){this.Wa=
!0}ab(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}cb(a){return!this.ab(a)}async I(a){return"cordova"===this.h&&(a.startsWith("file:")||this.xa&&this.cb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.ja(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async tb(a){const c=a.filename;switch(a.as){case "text":return await this.$a(c);case "buffer":return await this.ja(c);default:throw Error("unsupported type");}}Ha(a){const c=
window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async $a(a){a=await this.Ha(a);return await ma(a)}na(){if(y.length&&!(8<=z)){z++;var a=y.shift();this.nb(a.filename,a.Qb,a.Jb)}}ja(a){return new Promise((c,d)=>{y.push({filename:a,Qb:e=>{z--;this.na();c(e)},Jb:e=>{z--;this.na();d(e)}});this.na()})}async nb(a,c,d){try{const e=await this.Ha(a),f=await na(e);c(f)}catch(e){d(e)}}Bb(){var a={type:"ready"};if("windows-webview2"===
this.h)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.h)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async mb(){const a=[];for(const [c,d]of Object.entries(this.B))a.push(this.lb(c,d));await Promise.all(a)}async lb(a,c){if("object"===typeof c)this.B[a]=new Blob([c.str],{type:c.type}),this.fa[a]=c.str;else{let d=await this.pb(c);d||(d=this.ob(c));this.B[a]=d}}async pb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}ob(a){a=this.Ab(a);return this.jb(a.data,a.Mb)}Ab(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Mb:a,data:d}}jb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const E=self.D;function wa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const xa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),F={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ya={dispatchUserScriptEvent:!0},G={dispatchRuntimeEvent:!0};
function za(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Aa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function H(b){b=URL.createObjectURL(b);try{return await Aa(b)}finally{URL.revokeObjectURL(b)}}
function Ba(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ca(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await H(b);var d=await Ba(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await H(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await H(b)}
function I(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Da=new Set(["input","textarea","datalist","select"]),Ea=new Set(["canvas","body","html"]);function J(b){b.target.tagName&&Ea.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Fa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await H(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ca(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let K=!1;document.addEventListener("pause",()=>K=!0);document.addEventListener("resume",()=>K=!1);function ua(b){b.Ua=!0;b.za=b.i.A();b.V=b.i.v()}async function Ga(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function La(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ma(b){return await self.C3_GetSvgImageSize(b.blob)}function Na(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Oa(b){self.setTimeout(()=>{b.Ta=!0},1E3);"cordova"===b.i.h?(document.addEventListener("pause",()=>L(b,!0)),document.addEventListener("resume",()=>L(b,!1))):document.addEventListener("visibilitychange",()=>L(b,document.hidden));return{isSuspended:!(!document.hidden&&!K)}}
function Pa(b){b.Sa||(b.Sa=!0,window.addEventListener("deviceorientation",a=>{b.l||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},F)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},F)}))}
function Qa(b){b.Ra||(b.Ra=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},F)}}))}async function Ra(b){await za(b.url)}
function Sa(b,a){b.Va=a.message;-1===b.ua&&(b.ua=setTimeout(()=>{b.ua=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Va)},250))}function M(b){if(!b.l){var a=E.P();a&&"any"!==b.Ea&&Ta(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.A(),innerHeight:b.v()})}}function N(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:E.P(),innerWidth:b.A(),innerHeight:b.v()})}
function L(b,a){a?b.i.kb():b.i.ra();l(b,"visibilitychange",{hidden:a})}function Ua(b,a,c){"Backspace"===c.key&&J(c);if(!b.l){var d=xa.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},F)}}
function P(b,a,c,d){b.l||wa(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function R(b){window!==window.top&&window.focus();Va(b.target)&&document.activeElement&&!Va(document.activeElement)&&document.activeElement.blur()}
function S(b,a,c){if(!b.l){var d=0;"mouse"===c.pointerType&&(d=b.X);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},F);"mouse"===c.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),P(b,d,c,ya),b.X=c.buttons)}}
function T(b,a,c){if(!b.l&&!wa(c)){var d=b.X;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},F);b.X=c.buttons;P(b,c.type,c,ya)}}
function U(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
F)}}function V(b,a,c){document.body.style.transform="";b.s=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Wa(b,a,c,d){const e=b.A(),f=b.v();b.L=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.P()}):10>d&&Xa(b,e,f,d+1)}
function Xa(b,a,c,d){-1!==b.L&&clearTimeout(b.L);b.L=setTimeout(()=>Wa(b,a,c,d),48)}
function Ta(b){b=b.Ea;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Va(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
E.G(class extends self.Ia{constructor(b){super(b,"runtime");this.Xa=!0;this.Ua=!1;this.L=-1;this.Ea="any";this.Ra=this.Sa=!1;this.ga=document.createElement("div");this.ga.className="c3-screen-reader-text";this.ga.setAttribute("aria-live","polite");document.body.appendChild(this.ga);this.F=null;this.l=!1;this.Va="";this.ua=-1;this.Ta=!1;this.za=b.A();this.V=b.v();this.s=this.Z=0;b.g("canvas","update-size",d=>{var e=this.i;e.Wa||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",
e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Xa&&(e.style.display="",this.Xa=!1))});b.g("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.g("runtime","load-webfonts",d=>Ga(d));b.g("runtime","raster-svg-image",d=>La(d));b.g("runtime","get-svg-image-size",
d=>Ma(d));b.g("runtime","set-target-orientation",d=>{this.Ea=d.targetOrientation});b.g("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.g("runtime","post-to-debugger",d=>Na(d));b.g("runtime","go-to-script",d=>Na(d));b.g("runtime","before-start-ticking",()=>Oa(this));b.g("runtime","debug-highlight",d=>{if(d.show){this.F||(this.F=document.createElement("div"),this.F.id="inspectOutline",document.body.appendChild(this.F));var e=this.F;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.F&&(this.F.style.display="none")});b.g("runtime","enable-device-orientation",()=>Pa(this));b.g("runtime","enable-device-motion",()=>Qa(this));b.g("runtime","add-stylesheet",d=>Ra(d));b.g("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.g("runtime","alert",d=>{alert(d.message)});b.g("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ga.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.g("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.g("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.hb()});b.g("runtime","export-to-video-progress",d=>Sa(this,d));b.g("runtime","exported-to-video",d=>{window.Hb({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.g("runtime","exported-to-image-sequence",d=>{window.Hb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||I(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",J);window.addEventListener("gesturehold",J);c.addEventListener("selectstart",J);c.addEventListener("gesturehold",
J);window.addEventListener("touchstart",J,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",J,{passive:!1}),c.addEventListener("pointerdown",J)):c.addEventListener("touchstart",J);this.X=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Ua){var d=this.A();var e=this.v();if(this.i.Ka()){if(this.Ta){if(this.za===
d&&e<this.V){this.Z=this.V-e;V(this,this.V,this.Z);d=void 0;break a}0<this.Z&&(this.Z=0,V(this,e,this.Z))}this.za=d;this.V=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.P()});this.i.la()&&(-1!==this.L&&clearTimeout(this.L),Wa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",()=>M(this));window.addEventListener("fullscreenerror",
d=>N(this,d));window.addEventListener("webkitfullscreenerror",d=>N(this,d));window.addEventListener("mozfullscreenerror",d=>N(this,d));if(b.la())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):I(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(E.Qa(!0),M(this)):"exited-fullscreen"===d?(E.Qa(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Ba=new Set;this.Fb=new WeakSet;this.Db=!1}Ga(){window.addEventListener("focus",()=>{l(this,"window-focus",null,G)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}l(this,"window-blur",{parentHasFocus:a},G);this.X=0});window.addEventListener("focusin",a=>{a=a.target;(Da.has(a.tagName.toLowerCase())||I(a))&&l(this,"keyboard-blur",null,G)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("dblclick",a=>P(this,"dblclick",a,F));window.addEventListener("wheel",a=>{this.l||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,
deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},F)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{R(a);S(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{S(this,"pointermove",a)}):window.addEventListener("pointermove",a=>S(this,"pointermove",a)),window.addEventListener("pointerup",a=>S(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>S(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{R(a);T(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>T(this,"pointermove",a)),window.addEventListener("mouseup",a=>T(this,"pointerup",a)),window.addEventListener("touchstart",a=>{R(a);U(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>U(this,"pointermove",a)),window.addEventListener("touchend",a=>U(this,"pointerup",a)),window.addEventListener("touchcancel",a=>U(this,"pointercancel",a)));const b=
()=>this.qa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.bb()&&!this.i.Ka()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{V(this,this.v(),navigator.virtualKeyboard.boundingRect.height)}))}A(){return this.i.A()}v(){return this.i.v()}qa(){var b=
[...this.Ba];this.Ba.clear();if(!this.Db)for(const a of b)(b=a.play())&&b.catch(()=>{this.Fb.has(a)||this.Ba.add(a)})}});"use strict";async function sa(b){if(b.Cb)throw Error("already initialised");b.Cb=!0;var a=b.C.pa(("playable-ad"===b.C.h?b.C.K:"")+"dispatchworker.js");b.sa=await b.C.ka(a,b.R,{name:"DispatchWorker"});a=new MessageChannel;b.wa=a.port1;b.sa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Ca=await va(b)}function ta(b){return[b.wa,b.Ca]}
async function va(b){const a=b.Ya.length;var c=b.C.pa(("playable-ad"===b.C.h?b.C.K:"")+"jobworker.js");c=await b.C.ka(c,b.R,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.sa.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ya.push(c);return e.port1}
self.fb=class{constructor(b){this.C=b;this.R=b.m;this.R="preview"===b.h?this.R+"workers/":this.R+b.K;this.Eb=Math.min(navigator.hardwareConcurrency||2,16);this.sa=null;this.Ya=[];this.Ca=this.wa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.D({Rb:!0,Sb:"workermain.js",N:["scripts/c3runtime.js"],ha:[],Fa:"",Ob:"scripts/",ia:[],Za:"html5"}));"use strict";function W(b){b.stopPropagation()}
self.D.G(class extends self.O{constructor(b){super(b,"button")}H(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",W);d.addEventListener("pointermove",
W);d.addEventListener("pointerrawupdate",W);d.addEventListener("pointerup",W);d.addEventListener("mousedown",W);d.addEventListener("mouseup",W);d.addEventListener("keydown",W);d.addEventListener("keyup",W);c.addEventListener("click",()=>u(this,"click",b,{isChecked:c.checked}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.u(d,a);return d}oa(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}u(b,a){const c="input"===b.tagName.toLowerCase()?b:b.firstChild;c.checked=a.isChecked;
c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";function X(b){b.stopPropagation()}function Ya(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.D.G(class extends self.O{constructor(b){super(b,"text-input");r(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}H(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",X);c.addEventListener("pointermove",X);c.addEventListener("pointerrawupdate",X);c.addEventListener("pointerup",X);c.addEventListener("mousedown",
X);c.addEventListener("mouseup",X);c.addEventListener("keydown",Ya);c.addEventListener("keyup",Ya);c.addEventListener("click",e=>{e.stopPropagation();u(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();u(this,"dblclick",b)});c.addEventListener("input",()=>q(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.u(c,a);return c}u(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function Y(b){b.stopPropagation()}function Za(b){const a=document.createElement("option");a.text=b;return a}function $a(b){const a=b.selectedIndex,c=[];for(let d=0,e=b.length;d<e;++d)b.options[d].selected&&c.push(d);return{selectedIndex:a,selectedIndices:c}}
self.D.G(class extends self.O{constructor(b){super(b,"list");r(this,"set-selected-index",(a,c)=>{a.selectedIndex=c.selectedIndex});r(this,"add-item",(a,c)=>{const d=c.index;c=Za(c.text);0>d?a.add(c):a.add(c,d)});r(this,"remove-item",(a,c)=>{a.remove(c.index)});r(this,"set-item",(a,c)=>{a.options[c.index].text=c.text});r(this,"clear",a=>{a.innerHTML=""});r(this,"load-state",(a,c)=>{a.innerHTML="";for(const d of c.items)a.add(Za(d));a.selectedIndex=c.selectedIndex;for(const d of c.selectedIndices)if(c=
a.options[d])c.selected=!0})}H(b,a){const c=a.isDropdown,d=a.isMultiSelect,e=a.items,f=document.createElement("select");f.style.position="absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;c||(f.size=2);for(const g of e)f.add(Za(g));f.addEventListener("pointerdown",Y);f.addEventListener("pointermove",Y);f.addEventListener("pointerrawupdate",Y);f.addEventListener("pointerup",Y);f.addEventListener("mousedown",Y);f.addEventListener("mouseup",Y);f.addEventListener("click",
g=>{g.stopPropagation();u(this,"click",b,$a(f))});f.addEventListener("dblclick",g=>{g.stopPropagation();u(this,"dblclick",b,$a(f))});f.addEventListener("change",()=>q(this,"change",b,$a(f)));a.id&&(f.id=a.id);a.className&&(f.className=a.className);this.u(f,a);return f}u(b,a){b.title=a.title;b.disabled=!a.isEnabled;b.multiple=!!a.isMultiSelect}});"use strict";function Z(b){b.stopPropagation()}
self.D.G(class extends self.O{constructor(b){super(b,"sliderbar")}H(b,a){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Z);c.addEventListener("keyup",Z);c.addEventListener("click",
()=>u(this,"click",b));c.addEventListener("change",()=>q(this,"change",b,{value:parseFloat(c.value)}));c.addEventListener("input",()=>q(this,"input",b,{value:parseFloat(c.value)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.u(c,a);return c}u(b,a){b.max=a.max;b.min=a.min;b.step=a.step;b.value=a.value;b.disabled=!a.isEnabled;b.title=a.title}});"use strict";function ab(b,a,c){bb(b,a,URL.createObjectURL(new Blob([c.html],{type:"text/html"})));b.ea=!0}
function bb(b,a,c){a.src&&a.src.startsWith("blob:")&&b.ea&&URL.revokeObjectURL(a.src);a.src=c}
self.D.G(class extends self.O{constructor(b){super(b,"iframe");this.ea=!1;r(this,"navigate-url",(a,c)=>{bb(this,a,c.url);this.ea=!1});r(this,"display-html",(a,c)=>ab(this,a,c))}H(b,a){b=document.createElement("iframe");b.style.position="absolute";b.style.border="none";var c=navigator.userAgent;/iphone|ipad|ipod/i.test(c)&&(c=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(c),c=parseInt(c[c.length-1]),12>=c||isNaN(c))&&(b.setAttribute("noresize","noresize"),b.setAttribute("scrolling","no"));a.isVisible||
(b.style.display="none");a.id&&(b.id=a.id);a.allow&&(b.setAttribute("allow",a.allow),a.allow.includes("fullscreen")&&b.setAttribute("allowfullscreen",""));a.enableSandbox&&b.setAttribute("sandbox",a.sandbox);a.url?b.src=a.url:a.html&&ab(this,b,a);return b}u(){}Ja(b){bb(this,b,"");this.ea=!1}});
