function l(a,b,c,d){a.D.Vb(a.Sa,b,c,d)}function aa(a,b,c){return a.D.Rd(a.Sa,b,c)}function ba(a,b,c,d){a.D.Y?l(a,b,c,d):a.D.ae()._OnMessageFromDOM({type:"event",component:a.Sa,handler:b,dispatchOpts:d||null,data:c,responseId:null})}function n(a,b,c){a.D.s(a.Sa,b,c)}function ca(a,b){for(const [c,d]of b)n(a,c,d)}window.pb=class{constructor(a,b){this.D=a;this.Sa=b}Pc(){}pa(){}};window.Le=class{constructor(){}};"use strict";class da{constructor(a){this.jc=a;this.nc=!1;this.uc=!0}}
function fa(a,b){const c=b.elementId,d=a.ta(c,b),e=new da(d);a.Ua.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.uc=!!b.isVisible;b=a.$b(d);b.addEventListener("focus",()=>{ha(a,"elem-focused",c)});b.addEventListener("blur",()=>{ha(a,"elem-blurred",c)});a.sb&&document.body.appendChild(d)}function t(a,b,c){n(a,b,d=>{const e=w(a,d.elementId);return c(e,d)})}function w(a,b){a=a.Ua.get(b);if(!a)throw Error(`no element with id ${b}`);return a.jc}
function ha(a,b,c,d){d||(d={});d.elementId=c;l(a,b,d)}function D(a,b,c,d){d||(d={});d.elementId=c;ba(a,b,d)}
window.Ca=class extends self.pb{constructor(a,b){super(a,b);this.Ua=new Map;this.sb=!0;ca(this,[["create",c=>fa(this,c)],["destroy",c=>{c=c.elementId;const d=w(this,c);this.Rc(d);this.sb&&d.parentElement.removeChild(d);this.Ua.delete(c)}],["set-visible",c=>{if(this.sb){var d=this.Ua.get(c.elementId),e=d.jc;d.nc?e.style.display=c.isVisible?"":"none":d.uc=!!c.isVisible}}],["update-position",c=>{if(this.sb){var d=this.Ua.get(c.elementId),e=d.jc;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.nc||(d.nc=!0,d.uc&&(e.style.display=""))}}],["update-state",c=>{const d=w(this,c.elementId);this.R(d,c)}],["focus",c=>{const d=this.$b(w(this,c.elementId));c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=w(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{w(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{w(this,
c.elementId).removeAttribute(c.name)}]]);t(this,"get-element",c=>c)}ta(){throw Error("required override");}Rc(){}R(){throw Error("required override");}$b(a){return a}};"use strict";const ka=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),la=/android/i.test(navigator.userAgent),ma=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let na=0;
function oa(a){const b=document.createElement("script");b.async=!1;b.type="module";return a.Be?new Promise(c=>{const d="c3_resolve_"+na;++na;self[d]=c;b.textContent=a.Fe+`\n\nself["${d}"]();`;document.head.appendChild(b)}):new Promise((c,d)=>{b.onload=c;b.onerror=d;b.src=a;document.head.appendChild(b)})}let pa=!1,sa=!1;function ta(){if(!pa){try{new Worker("blob://",{get type(){sa=!0}})}catch(a){}pa=!0}return sa}let E=new Audio;
const ua={"audio/webm; codecs=opus":!!E.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!E.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!E.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!E.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!E.canPlayType("audio/mp4"),"audio/mpeg":!!E.canPlayType("audio/mpeg")};E=null;async function va(a){a=await wa(a);return(new TextDecoder("utf-8")).decode(a)}
function wa(a){return new Promise((b,c)=>{const d=new FileReader;d.onload=e=>b(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(a)})}const xa=[];let ya=0;window.RealFile=window.File;const za=[],Aa=new Map,Ba=new Map;let Da=0;const Ea=[];self.runOnStartup=function(a){if("function"!==typeof a)throw Error("runOnStartup called without a function");Ea.push(a)};const Fa=new Set(["cordova","playable-ad","instant-games"]);let Ga=!1;
window.ea=class a{constructor(b){this.Y=b.He;this.ab=null;this.X="";this.Ja=b.Ee;this.nb={};this.zc=this.Na=null;this.wb=[];this.N=this.jb=null;this.ld=!1;this.Za=null;this.Ha=-1;this.se=()=>this.he();this.Fc=[];this.v=b.ud;this.tc="file"===location.protocol.substr(0,4);!this.Y||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ta()||(this.Y=!1);this.Y&&ma&&(this.Y=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.Y=!1;if("cordova"===this.v&&this.Y)if(la){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.Y=!1)}else this.Y=!1;this.Db=this.ma=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.s("runtime","cordova-fetch-local-file",c=>this.de(c));this.s("runtime","create-job-worker",()=>this.ee());"cordova"===this.v?document.addEventListener("deviceready",()=>this.Yc(b)):this.Yc(b)}Pd(){return ka&&
"cordova"===this.v}Ub(){const b=navigator.userAgent;return ka&&Fa.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(b)}Nd(){return la}Uc(){return la&&Fa.has(this.v)}async Yc(b){"macos-wkwebview"===this.v&&this.le();if("playable-ad"===this.v){this.ma=self.c3_base64files;this.Db={};await this.Xd();for(let d=0,e=b.Oa.length;d<e;++d){var c=b.Oa[d];this.Db.hasOwnProperty(c)?b.Oa[d]={Be:!0,Fe:this.Db[c]}:this.ma.hasOwnProperty(c)&&(b.Oa[d]=URL.createObjectURL(this.ma[c]))}b.Ob=[]}if("nwjs"===
this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Td(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}b.De?this.X=b.De:(c=location.origin,this.X=("null"===c?"file:///":c)+location.pathname,c=this.X.lastIndexOf("/"),-1!==c&&(this.X=this.X.substr(0,c+1)));b.Je&&(this.nb=b.Je);c=new MessageChannel;this.ab=c.port1;this.ab.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.ge(d));this.Za=new self.Qd(this);
await Ha(this.Za);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.Y?await this.ce(b,c.port2):await this.be(b,c.port2)}ac(b){b=this.nb.hasOwnProperty(b)?this.nb[b]:b.endsWith("/workermain.js")&&this.nb.hasOwnProperty("workermain.js")?this.nb["workermain.js"]:"playable-ad"===this.v&&this.ma.hasOwnProperty(b)?
this.ma[b]:b;b instanceof Blob&&(b=URL.createObjectURL(b));return b}async Sb(b,c,d){if(b.startsWith("blob:"))return new Worker(b,d);if("cordova"===this.v&&this.tc)return b=await this.Rb(d.Ae?b:this.Ja+b),new Worker(URL.createObjectURL(new Blob([b],{type:"application/javascript"})),d);b=new URL(b,c);if(location.origin!==b.origin){b=await fetch(b);if(!b.ok)throw Error("failed to fetch worker script");b=await b.blob();return new Worker(URL.createObjectURL(b),d)}return new Worker(b,d)}ka(){return Math.max(window.innerWidth,
1)}fa(){return Math.max(window.innerHeight,1)}Xc(b){var c=this.X,d=location.href,e=this.ka(),f=this.fa(),g=window.devicePixelRatio,h=a.Qa(),m=b.Pe,z=window.cr_previewImageBlobs||this.ma,r=window.cr_previewProjectFileBlobs,O=window.cr_previewProjectFiles,A=window.Ne||"";b=b.ud;var v=(new URLSearchParams(self.location.search)).has("debug"),p=this.Za;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:z,previewProjectFileBlobs:r,
previewProjectFileSWUrls:O,swClientId:A,exportType:b,isDebug:v,ife:!!self.Oe,jobScheduler:{inputPort:p.rc,outputPort:p.Dc,maxNumWorkers:p.oe},supportedAudioFormats:ua,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Ja+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Ja+"opus.wasm.wasm",isFileProtocol:this.tc,isiOSCordova:this.Pd(),isiOSWebView:this.Ub(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ce(b,c){const d=this.ac(b.Ie);"preview"===this.v?(this.Na=new Worker("previewworker.js",
{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const z=r=>{this.Na.removeEventListener("message",z);r.data&&"ok"===r.data.type?h():m()};this.Na.addEventListener("message",z);this.Na.postMessage({type:"construct-worker-init","import":(new URL(d,this.X)).toString()})})):this.Na=await this.Sb(d,this.X,{type:"module",name:"Runtime",Ae:!0});this.N=document.createElement("canvas");this.N.style.display="none";const e=this.N.transferControlToOffscreen();document.body.appendChild(this.N);window.c3canvas=
this.N;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=b.Ob||[],g=b.Oa;f=await Promise.all(f.map(h=>this.Ea(h)));g=await Promise.all(g.map(h=>this.Ea(h)));if("cordova"===this.v)for(let h=0,m=b.Nb.length;h<m;++h){const z=b.Nb[h],r=z[0];if(r===b.Nc||"scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))z[1]=await this.Ea(r)}this.Na.postMessage(Object.assign(this.Xc(b),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:b.Nb,
mainProjectScript:b.Nc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...Ia(this.Za)]);this.wb=za.map(h=>new h(this));this.Wc();Ja(this.jb);self.c3_callFunction=(h,m)=>aa(this.jb,"js-invoke-function",{name:h,params:m});"preview"===this.v&&(self.goToLastErrorScript=()=>this.Vb("runtime","go-to-last-error-script"))}async be(b,c){this.N=document.createElement("canvas");this.N.style.display="none";document.body.appendChild(this.N);window.c3canvas=this.N;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
this.wb=za.map(g=>new g(this));this.Wc();var d=b.Oa.map(g=>"string"===typeof g?(new URL(g,this.X)).toString():g);if(Array.isArray(b.Ob)){var e=[...b.Ob].map(g=>g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Ea(g)));await Promise.all(d.map(g=>oa(g)));d=self.C3_ProjectScriptsStatus;e=b.Nc;const f=b.Nb;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ea(h),await oa(h),"preview"!==this.v||d[g]||this.$c(g,"main script did not run to completion")}catch(m){this.$c(g,
m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ea(h),await oa(h);"preview"===this.v&&"object"!==typeof self.Ke.Me?(this.rb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(b=Object.assign(this.Xc(b),{isInWorker:!1,messagePort:c,canvas:this.N,runOnStartupFunctions:Ea}),Ja(this.jb),
this.Zc(),this.zc=self.C3_CreateRuntime(b),await self.C3_InitRuntime(this.zc,b))}$c(b,c){this.rb();console.error(`[Preview] Failed to load project main script (${b}): `,c);alert(`Failed to load project main script (${b}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Zc(){this.rb()}rb(){const b=window.xe;b&&(b.parentElement.removeChild(b),window.xe=null)}async ee(){const b=await Ka(this.Za);return{outputPort:b,transferables:[b]}}ae(){if(this.Y)throw Error("not available in worker mode");
return this.zc}Vb(b,c,d,e){this.ab.postMessage({type:"event",component:b,handler:c,dispatchOpts:e||null,data:d,responseId:null},void 0)}Rd(b,c,d){const e=Da++,f=new Promise((g,h)=>{Ba.set(e,{resolve:g,reject:h})});this.ab.postMessage({type:"event",component:b,handler:c,dispatchOpts:null,data:d,responseId:e},void 0);return f}_OnMessageFromRuntime(b){const c=b.type;if("event"===c)return this.fe(b);if("result"===c)this.ie(b);else if("runtime-ready"===c)this.je();else if("alert-error"===c)this.rb(),alert(b.message);
else if("creating-runtime"===c)this.Zc();else throw Error(`unknown message '${c}'`);}fe(b){const c=b.component,d=b.handler,e=b.data,f=b.responseId;if(b=Aa.get(c))if(b=b.get(d)){var g=null;try{g=b(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.qb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.qb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.qb(f,!1,""+h)}):this.qb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);
else console.warn(`[DOM] No event handlers for component '${c}'`)}qb(b,c,d){let e;d&&d.transferables&&(e=d.transferables);this.ab.postMessage({type:"result",responseId:b,isOk:c,result:d},e)}ie(b){const c=b.responseId,d=b.isOk;b=b.result;const e=Ba.get(c);d?e.resolve(b):e.reject(b);Ba.delete(c)}s(b,c,d){let e=Aa.get(b);e||(e=new Map,Aa.set(b,e));if(e.has(c))throw Error(`[DOM] Component '${b}' already has handler '${c}'`);e.set(c,d)}static ja(b){if(za.includes(b))throw Error("DOM handler already added");
za.push(b)}Wc(){for(const b of this.wb)if("runtime"===b.Sa){this.jb=b;return}throw Error("cannot find runtime DOM handler");}ge(b){this.Vb("debugger","message",b)}je(){for(const b of this.wb)b.Pc()}static Qa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||Ga)}static ad(b){Ga=!!b}Td(b){this.Fc.push(b);this.cc()}cc(){-1===this.Ha&&this.Fc.length&&(this.Ha=requestAnimationFrame(this.se))}Vd(){-1!==this.Ha&&(cancelAnimationFrame(this.Ha),this.Ha=
-1)}he(){this.Ha=-1;for(const b of this.Fc)b();this.cc()}bc(){this.jb.bc()}Sd(){this.ld=!0}Md(b){return/^(?:[a-z\-]+:)?\/\//.test(b)||"data:"===b.substr(0,5)||"blob:"===b.substr(0,5)}Od(b){return!this.Md(b)}async Ea(b){return"cordova"===this.v&&(b.startsWith("file:")||this.tc&&this.Od(b))?(b.startsWith(this.X)&&(b=b.substr(this.X.length)),b=await this.Rb(b),URL.createObjectURL(new Blob([b],{type:"application/javascript"}))):b}async de(b){const c=b.filename;switch(b.as){case "text":return await this.Kd(c);
case "buffer":return await this.Rb(c);default:throw Error("unsupported type");}}Qc(b){const c=window.cordova.file.applicationDirectory+"www/"+b;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Kd(b){b=await this.Qc(b);return await va(b)}Zb(){if(xa.length&&!(8<=ya)){ya++;var b=xa.shift();this.Yd(b.filename,b.Ge,b.ye)}}Rb(b){return new Promise((c,d)=>{xa.push({filename:b,Ge:e=>{ya--;this.Zb();c(e)},ye:e=>{ya--;this.Zb();d(e)}});this.Zb()})}async Yd(b,c,d){try{const e=
await this.Qc(b),f=await wa(e);c(f)}catch(e){d(e)}}le(){var b={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(b));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(b));else throw Error("cannot send wrapper message");}async Xd(){const b=[];for(const [c,d]of Object.entries(this.ma))b.push(this.Wd(c,d));await Promise.all(b)}async Wd(b,c){if("object"===typeof c)this.ma[b]=new Blob([c.str],{type:c.type}),
this.Db[b]=c.str;else{let d=await this.$d(c);d||(d=this.Zd(c));this.ma[b]=d}}async $d(b){try{return await (await fetch(b)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Zd(b){b=this.ke(b);return this.Ud(b.data,b.Ce)}ke(b){var c=b.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=b.substring(c+
1);c=b.substring(5,c).split(";");b=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ce:b,data:d}}Ud(b,c){var d=b.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=b.charCodeAt(m++)|b.charCodeAt(m++)<<8|b.charCodeAt(m++)<<16|b.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=b.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const F=self.ea;
function La(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents}const Ma=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),G={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Na={dispatchUserScriptEvent:!0},Oa={dispatchRuntimeEvent:!0};
function Pa(a){return new Promise((b,c)=>{const d=document.createElement("link");d.onload=()=>b(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=a;document.head.appendChild(d)})}function Qa(a){return new Promise((b,c)=>{const d=new Image;d.onload=()=>b(d);d.onerror=e=>c(e);d.src=a})}async function Ra(a){a=URL.createObjectURL(a);try{return await Qa(a)}finally{URL.revokeObjectURL(a)}}
function Sa(a){return new Promise((b,c)=>{let d=new FileReader;d.onload=e=>b(e.target.result);d.onerror=e=>c(e);d.readAsText(a)})}
async function Ta(a,b,c){if(!/firefox/i.test(navigator.userAgent))return await Ra(a);var d=await Sa(a);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await Ra(a)}e.setAttribute("width",b+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);a=new Blob([d],{type:"image/svg+xml"});return await Ra(a)}
function Ua(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);return!1}const Va=new Set(["input","textarea","datalist","select"]),Wa=new Set(["canvas","body","html"]);function H(a){a.target.tagName&&Wa.has(a.target.tagName.toLowerCase())&&a.preventDefault()}function Xa(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()}
self.C3_GetSvgImageSize=async function(a){a=await Ra(a);if(0<a.width&&0<a.height)return[a.width,a.height];a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const b=a.getBoundingClientRect();document.body.removeChild(a);return[b.width,b.height]};self.C3_RasterSvgImageBlob=async function(a,b,c,d,e){a=await Ta(a,b,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(a,0,0,b,c);return f};
let Ya=!1;document.addEventListener("pause",()=>Ya=!0);document.addEventListener("resume",()=>Ya=!1);function Ja(a){a.hd=!0;a.yc=a.D.ka();a.$a=a.D.fa()}async function Za(a){await Promise.all(a.webfonts.map(async b=>{b=new FontFace(b.name,`url('${b.url}')`);document.fonts.add(b);await b.load()}))}
async function $a(a){var b=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);b=b?await createImageBitmap(a,b):await createImageBitmap(a);return{imageBitmap:b,transferables:[b]}}async function ab(a){return await self.C3_GetSvgImageSize(a.blob)}function bb(a){window.c3_postToMessagePort&&(a.from="runtime",window.c3_postToMessagePort(a))}
function cb(a){self.setTimeout(()=>{a.gd=!0},1E3);"cordova"===a.D.v?(document.addEventListener("pause",()=>db(a,!0)),document.addEventListener("resume",()=>db(a,!1))):document.addEventListener("visibilitychange",()=>db(a,document.hidden));return{isSuspended:!(!document.hidden&&!Ya)}}
function eb(a){a.cd||(a.cd=!0,window.addEventListener("deviceorientation",b=>{a.T||l(a,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},G)}),window.addEventListener("deviceorientationabsolute",b=>{a.T||l(a,"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},G)}))}
function fb(a){a.bd||(a.bd=!0,window.addEventListener("devicemotion",b=>{if(!a.T){var c=null,d=b.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=b.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=b.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(a,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:b.interval,timeStamp:b.timeStamp},G)}}))}async function gb(a){await Pa(a.url)}
function hb(a,b){a.jd=b.message;-1===a.kc&&(a.kc=setTimeout(()=>{a.kc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=a.jd)},250))}function ib(a){if(!a.T){var b=F.Qa();b&&"any"!==a.Kc&&jb(a);l(a,"fullscreenchange",{isFullscreen:b,innerWidth:a.ka(),innerHeight:a.fa()})}}function kb(a,b){console.warn("[Construct] Fullscreen request failed: ",b);l(a,"fullscreenerror",{isFullscreen:F.Qa(),innerWidth:a.ka(),innerHeight:a.fa()})}
function db(a,b){b?a.D.Vd():a.D.cc();l(a,"visibilitychange",{hidden:b})}function lb(a,b,c){"Backspace"===c.key&&H(c);if(!a.T){var d=Ma.get(c.code)||c.code;ba(a,b,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},G)}}
function mb(a,b,c,d){a.T||La(c)||ba(a,b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+a.Z,pageX:c.pageX,pageY:c.pageY+a.Z,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function nb(a){window!==window.top&&window.focus();ob(a.target)&&document.activeElement&&!ob(document.activeElement)&&document.activeElement.blur()}
function qb(a,b,c){if(!a.T){var d=0;"mouse"===c.pointerType&&(d=a.bb);ba(a,b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+a.Z,pageX:c.pageX,pageY:c.pageY+a.Z,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},G);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===b?d="mousedown":"pointerup"===b&&(d="mouseup"),mb(a,d,c,Na),a.bb=c.buttons)}}
function rb(a,b,c){if(!a.T&&!La(c)){var d=a.bb;"pointerdown"===b&&0!==d?b="pointermove":"pointerup"===b&&0!==c.buttons&&(b="pointermove");ba(a,b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+a.Z,pageX:c.pageX,pageY:c.pageY+a.Z,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},G);a.bb=c.buttons;mb(a,c.type,c,Na)}}
function sb(a,b,c){if(!a.T)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];ba(a,b,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+a.Z,pageX:f.pageX,pageY:f.pageY+a.Z,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
G)}}function tb(a,b,c){document.body.style.transform="";a.Z=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),b=(d.top+d.bottom)/2-(b-c)/2,b>c&&(b=c),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`,a.Z=b))}}function ub(a,b,c,d){const e=a.ka(),f=a.fa();a.Ka=-1;e!=b||f!=c?l(a,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.Qa()}):10>d&&vb(a,e,f,d+1)}
function vb(a,b,c,d){-1!==a.Ka&&clearTimeout(a.Ka);a.Ka=setTimeout(()=>ub(a,b,c,d),48)}
function jb(a){a=a.Kc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(b=>console.warn("[Construct] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));b||console.warn("[Construct] Failed to lock orientation")}catch(b){console.warn("[Construct] Failed to lock orientation: ",
b)}}function ob(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}
F.ja(class extends self.pb{constructor(a){super(a,"runtime");this.md=!0;this.hd=!1;this.Ka=-1;this.Kc="any";this.bd=this.cd=!1;this.Eb=document.createElement("div");this.Eb.className="c3-screen-reader-text";this.Eb.setAttribute("aria-live","polite");document.body.appendChild(this.Eb);this.ya=null;this.T=!1;this.jd="";this.kc=-1;this.gd=!1;this.yc=a.ka();this.$a=a.fa();this.Z=this.mb=0;a.s("canvas","update-size",d=>{var e=this.D;e.ld||(e=e.N,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.md&&(e.style.display="",this.md=!1))});a.s("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});a.s("runtime","load-webfonts",d=>Za(d));a.s("runtime","raster-svg-image",d=>$a(d));a.s("runtime","get-svg-image-size",
d=>ab(d));a.s("runtime","set-target-orientation",d=>{this.Kc=d.targetOrientation});a.s("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});a.s("runtime","post-to-debugger",d=>bb(d));a.s("runtime","go-to-script",d=>bb(d));a.s("runtime","before-start-ticking",()=>cb(this));a.s("runtime","debug-highlight",d=>{if(d.show){this.ya||(this.ya=document.createElement("div"),this.ya.id="inspectOutline",document.body.appendChild(this.ya));var e=this.ya;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.ya&&(this.ya.style.display="none")});a.s("runtime","enable-device-orientation",()=>eb(this));a.s("runtime","enable-device-motion",()=>fb(this));a.s("runtime","add-stylesheet",d=>gb(d));a.s("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});a.s("runtime","alert",d=>{alert(d.message)});
a.s("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.Eb.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
a.s("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});a.s("runtime","set-exporting-to-video",d=>{this.T=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.D.N.style.display="";this.D.Sd()});a.s("runtime","export-to-video-progress",d=>hb(this,d));a.s("runtime","exported-to-video",d=>{window.we({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});a.s("runtime","exported-to-image-sequence",d=>{window.we({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const b=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;b.has(e.tagName.toLowerCase())||Ua(e)||d.preventDefault()});const c=a.N;window.addEventListener("selectstart",H);window.addEventListener("gesturehold",H);c.addEventListener("selectstart",H);c.addEventListener("gesturehold",
H);window.addEventListener("touchstart",H,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",H,{passive:!1}),c.addEventListener("pointerdown",H)):c.addEventListener("touchstart",H);this.bb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Xa,{passive:!1});window.addEventListener("wheel",Xa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.T&&this.hd){var d=this.ka();var e=this.fa();if(this.D.Uc()){if(this.gd){if(this.yc===
d&&e<this.$a){this.mb=this.$a-e;tb(this,this.$a,this.mb);d=void 0;break a}0<this.mb&&(this.mb=0,tb(this,e,this.mb))}this.yc=d;this.$a=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.Qa()});this.D.Ub()&&(-1!==this.Ka&&clearTimeout(this.Ka),ub(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>ib(this));window.addEventListener("webkitfullscreenchange",()=>ib(this));window.addEventListener("mozfullscreenchange",
()=>ib(this));window.addEventListener("fullscreenerror",d=>kb(this,d));window.addEventListener("webkitfullscreenerror",d=>kb(this,d));window.addEventListener("mozfullscreenerror",d=>kb(this,d));if(a.Ub())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=
new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ua(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(F.ad(!0),ib(this)):"exited-fullscreen"===d?(F.ad(!1),ib(this)):console.warn("Unknown wrapper message: ",d)};this.Ac=new Set;this.qe=new WeakSet;this.ne=!1}Pc(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Oa)});window.addEventListener("blur",
()=>{try{var b=window.parent&&window.parent.document.hasFocus()}catch(c){b=!1}l(this,"window-blur",{parentHasFocus:b},Oa);this.bb=0});window.addEventListener("focusin",b=>{b=b.target;(Va.has(b.tagName.toLowerCase())||Ua(b))&&l(this,"keyboard-blur",null,Oa)});window.addEventListener("keydown",b=>lb(this,"keydown",b));window.addEventListener("keyup",b=>lb(this,"keyup",b));window.addEventListener("dblclick",b=>mb(this,"dblclick",b,G));window.addEventListener("wheel",b=>{this.T||l(this,"wheel",{clientX:b.clientX,
clientY:b.clientY+this.Z,pageX:b.pageX,pageY:b.pageY+this.Z,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},G)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",b=>{nb(b);qb(this,"pointerdown",b)}),this.D.Y&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",b=>{qb(this,"pointermove",b)}):window.addEventListener("pointermove",b=>qb(this,"pointermove",b)),window.addEventListener("pointerup",
b=>qb(this,"pointerup",b)),window.addEventListener("pointercancel",b=>qb(this,"pointercancel",b))):(window.addEventListener("mousedown",b=>{nb(b);rb(this,"pointerdown",b)}),window.addEventListener("mousemove",b=>rb(this,"pointermove",b)),window.addEventListener("mouseup",b=>rb(this,"pointerup",b)),window.addEventListener("touchstart",b=>{nb(b);sb(this,"pointerdown",b)}),window.addEventListener("touchmove",b=>sb(this,"pointermove",b)),window.addEventListener("touchend",b=>sb(this,"pointerup",b)),window.addEventListener("touchcancel",
b=>sb(this,"pointercancel",b)));const a=()=>this.bc();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0);this.D.Nd()&&!this.D.Uc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{tb(this,this.fa(),navigator.virtualKeyboard.boundingRect.height)}))}ka(){return this.D.ka()}fa(){return this.D.fa()}bc(){var a=
[...this.Ac];this.Ac.clear();if(!this.ne)for(const b of a)(a=b.play())&&a.catch(()=>{this.qe.has(b)||this.Ac.add(b)})}});"use strict";async function Ha(a){if(a.me)throw Error("already initialised");a.me=!0;var b=a.sa.ac(("playable-ad"===a.sa.v?a.sa.Ja:"")+"dispatchworker.js");a.ic=await a.sa.Sb(b,a.Ra,{name:"DispatchWorker"});b=new MessageChannel;a.rc=b.port1;a.ic.postMessage({type:"_init","in-port":b.port2},[b.port2]);a.Dc=await Ka(a)}function Ia(a){return[a.rc,a.Dc]}
async function Ka(a){const b=a.nd.length;var c=a.sa.ac(("playable-ad"===a.sa.v?a.sa.Ja:"")+"jobworker.js");c=await a.sa.Sb(c,a.Ra,{name:"JobWorker"+b});const d=new MessageChannel,e=new MessageChannel;a.ic.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:b,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);a.nd.push(c);return e.port1}
self.Qd=class{constructor(a){this.sa=a;this.Ra=a.X;this.Ra="preview"===a.v?this.Ra+"workers/":this.Ra+a.Ja;this.oe=Math.min(navigator.hardwareConcurrency||2,16);this.ic=null;this.nd=[];this.Dc=this.rc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ea({He:!0,Ie:"workermain.js",Oa:["scripts/c3runtime.js"],Nb:[],Nc:"",Ee:"scripts/",Ob:[],ud:"html5"}));"use strict";function I(a){a.stopPropagation()}
self.ea.ja(class extends self.Ca{constructor(a){super(a,"button")}ta(a,b){const c=document.createElement("input");var d=c;b.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",I);d.addEventListener("pointermove",
I);d.addEventListener("pointerrawupdate",I);d.addEventListener("pointerup",I);d.addEventListener("mousedown",I);d.addEventListener("mouseup",I);d.addEventListener("keydown",I);d.addEventListener("keyup",I);c.addEventListener("click",()=>D(this,"click",a,{isChecked:c.checked}));b.id&&(c.id=b.id);b.className&&(c.className=b.className);this.R(d,b);return d}$b(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}R(a,b){const c="input"===a.tagName.toLowerCase()?a:a.firstChild;c.checked=b.isChecked;
c.disabled=!b.isEnabled;a.title=b.title;a===c?c.value=b.text:a.lastChild.textContent=b.text}});"use strict";function wb(a){a.stopPropagation()}function xb(a){13!==a.which&&27!==a.which&&a.stopPropagation()}
self.ea.ja(class extends self.Ca{constructor(a){super(a,"text-input");t(this,"scroll-to-bottom",b=>{b.scrollTop=b.scrollHeight})}ta(a,b){let c;const d=b.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",wb);c.addEventListener("pointermove",wb);c.addEventListener("pointerrawupdate",wb);c.addEventListener("pointerup",wb);c.addEventListener("mousedown",
wb);c.addEventListener("mouseup",wb);c.addEventListener("keydown",xb);c.addEventListener("keyup",xb);c.addEventListener("click",e=>{e.stopPropagation();D(this,"click",a)});c.addEventListener("dblclick",e=>{e.stopPropagation();D(this,"dblclick",a)});c.addEventListener("input",()=>ha(this,"change",a,{text:c.value}));b.id&&(c.id=b.id);b.className&&(c.className=b.className);this.R(c,b);return c}R(a,b){a.value=b.text;a.placeholder=b.placeholder;a.title=b.title;a.disabled=!b.isEnabled;a.readOnly=b.isReadOnly;
a.spellcheck=b.spellCheck;b=b.maxLength;0>b?a.removeAttribute("maxlength"):a.setAttribute("maxlength",b)}});"use strict";function yb(a){a.stopPropagation()}function zb(a){const b=document.createElement("option");b.text=a;return b}function Ab(a){const b=a.selectedIndex,c=[];for(let d=0,e=a.length;d<e;++d)a.options[d].selected&&c.push(d);return{selectedIndex:b,selectedIndices:c}}
self.ea.ja(class extends self.Ca{constructor(a){super(a,"list");t(this,"set-selected-index",(b,c)=>{b.selectedIndex=c.selectedIndex});t(this,"add-item",(b,c)=>{const d=c.index;c=zb(c.text);0>d?b.add(c):b.add(c,d)});t(this,"remove-item",(b,c)=>{b.remove(c.index)});t(this,"set-item",(b,c)=>{b.options[c.index].text=c.text});t(this,"clear",b=>{b.innerHTML=""});t(this,"load-state",(b,c)=>{b.innerHTML="";for(const d of c.items)b.add(zb(d));b.selectedIndex=c.selectedIndex;for(const d of c.selectedIndices)if(c=
b.options[d])c.selected=!0})}ta(a,b){const c=b.isDropdown,d=b.isMultiSelect,e=b.items,f=document.createElement("select");f.style.position="absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;c||(f.size=2);for(const g of e)f.add(zb(g));f.addEventListener("pointerdown",yb);f.addEventListener("pointermove",yb);f.addEventListener("pointerrawupdate",yb);f.addEventListener("pointerup",yb);f.addEventListener("mousedown",yb);f.addEventListener("mouseup",yb);f.addEventListener("click",
g=>{g.stopPropagation();D(this,"click",a,Ab(f))});f.addEventListener("dblclick",g=>{g.stopPropagation();D(this,"dblclick",a,Ab(f))});f.addEventListener("change",()=>ha(this,"change",a,Ab(f)));b.id&&(f.id=b.id);b.className&&(f.className=b.className);this.R(f,b);return f}R(a,b){a.title=b.title;a.disabled=!b.isEnabled;a.multiple=!!b.isMultiSelect}});"use strict";function K(a){a.stopPropagation()}
self.ea.ja(class extends self.Ca{constructor(a){super(a,"sliderbar")}ta(a,b){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",K);c.addEventListener("pointermove",K);c.addEventListener("pointerrawupdate",K);c.addEventListener("pointerup",K);c.addEventListener("mousedown",K);c.addEventListener("mouseup",K);c.addEventListener("keydown",K);c.addEventListener("keyup",K);c.addEventListener("click",
()=>D(this,"click",a));c.addEventListener("change",()=>ha(this,"change",a,{value:parseFloat(c.value)}));c.addEventListener("input",()=>ha(this,"input",a,{value:parseFloat(c.value)}));b.id&&(c.id=b.id);b.className&&(c.className=b.className);this.R(c,b);return c}R(a,b){a.max=b.max;a.min=b.min;a.step=b.step;a.value=b.value;a.disabled=!b.isEnabled;a.title=b.title}});"use strict";function Bb(a,b,c){Cb(a,b,URL.createObjectURL(new Blob([c.html],{type:"text/html"})));a.zb=!0}
function Cb(a,b,c){b.src&&b.src.startsWith("blob:")&&a.zb&&URL.revokeObjectURL(b.src);b.src=c}
self.ea.ja(class extends self.Ca{constructor(a){super(a,"iframe");this.zb=!1;t(this,"navigate-url",(b,c)=>{Cb(this,b,c.url);this.zb=!1});t(this,"display-html",(b,c)=>Bb(this,b,c))}ta(a,b){a=document.createElement("iframe");a.style.position="absolute";a.style.border="none";var c=navigator.userAgent;/iphone|ipad|ipod/i.test(c)&&(c=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(c),c=parseInt(c[c.length-1]),12>=c||isNaN(c))&&(a.setAttribute("noresize","noresize"),a.setAttribute("scrolling","no"));b.isVisible||
(a.style.display="none");b.id&&(a.id=b.id);b.allow&&(a.setAttribute("allow",b.allow),b.allow.includes("fullscreen")&&a.setAttribute("allowfullscreen",""));b.enableSandbox&&a.setAttribute("sandbox",b.sandbox);b.url?a.src=b.url:b.html&&Bb(this,a,b);return a}R(){}Rc(a){Cb(this,a,"");this.zb=!1}});"use strict";async function Db(a,b){b=b.type;let c=!0;0===b?c=await Eb():1===b&&(c=await Fb());l(a,"permission-result",{type:b,result:c})}
async function Eb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(a){return console.warn("[Touch] Failed to request orientation permission: ",a),!1}}
async function Fb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(a){return console.warn("[Touch] Failed to request motion permission: ",a),!1}}self.ea.ja(class extends self.pb{constructor(a){super(a,"touch");n(this,"request-permission",b=>Db(this,b))}});"use strict";const Gb=[],Hb=2*Math.PI;function Ib(a){a%=Hb;0>a&&(a+=Hb);return a}
function Jb(a,b){switch(a.ra){case 0:return b;case 1:return Math.fround(b);case 2:return 2===a.Va&&(b=Ib(b),b/=Math.PI,b=32767*(b-1)),a=b|0,-32768>a?-32768:32767<a?32767:a;case 3:return 2===a.Va&&(b=Ib(b),b/=Hb,b*=255),a=b|0,0>a?0:255<a?255:a;default:return b}}function Kb(a,b,c,d){switch(a.ra){case 0:b.setFloat64(c,d);c+=8;break;case 1:b.setFloat32(c,d);c+=4;break;case 2:b.setInt16(c,d);c+=2;break;case 3:b.setUint8(c,d);c+=1;break;default:b.setFloat32(c,d),c+=4}return c}
function Lb(a,b){if(2!==a.Va)return b;2===a.ra?b=(b/32767+1)*Math.PI:3===a.ra&&(b=b/255*Hb);return b}function Mb(a,b,c,d,e){switch(a){case 0:return e?c:b;case 1:return b+d*(c-b);case 2:return b===c?a=0:(a=Math.sin(b)*Math.sin(c)+Math.cos(b)*Math.cos(c),a=1<=a?0:-1>=a?Math.PI:Math.acos(a)),0>=Math.cos(c)*Math.sin(b)-Math.sin(c)*Math.cos(b)?Ib(b+a*d):Ib(b-a*d);default:return e?c:b}}
class Nb{constructor(a,b,c,d,e,f){this.kd=a;this.Va=b;this.ra=c;this.lb=d;this.Ib=e;this.ed=f}Da(){return{tag:this.lb,interp:this.Va,userData:this.Ib,cvt:this.ed}}oa(){return this.Va}}class Ob{constructor(a,b){this.timestamp=a;this.data=b}}
class Qb{constructor(a,b,c){this.O=a;this.g=a.g;this.l=b;this.G=c;this.Ta=[];this.Ta.length=this.O.V.length;this.xc=this.Ab=0;this.sc=this.Gb=!1;this.I=[];this.B=this.j=this.ca=null}Da(){var a=[];for(let c=0,d=this.O.V.length;c<d;++c)a.push(this.oa(this.O.Fb,c));a={id:this.l,nid:this.G,isTimedOut:0===this.I.length?!1:this.I[this.I.length-1].timestamp<this.O.Fb-3E3,interpValues:a,latestUpdate:null};const b=0===this.I.length?null:this.I[this.I.length-1];b&&(a.latestUpdate={timestamp:b.timestamp,data:b.data});
return a}Xb(a,b){a=a.netValues;var c=this.O.V;const d=c.length;this.Gb=!1;for(let e=0;e<d;++e){const f=Jb(c[e],a[e]);this.Ta[e]!==f&&(this.Ta[e]=f,this.Ab=b,this.O.Ab=b)}a=b-this.Ab;b-=this.xc;c=this.O.dd;(this.Gb=100>a&&0===c?!0:1E3>a&&1>=c?95<=b:495<=b)&&this.O.fb++}Yb(a,b,c){const d=this.O.V;this.xc=c;a.setUint16(b,this.G);b+=2;for(let e=0,f=this.Ta.length;e<f;++e)b=Kb(d[e],a,b,this.Ta[e]);return b}Pb(a,b){for(let c=0,d=this.I.length;c<d;++c){const e=this.I[c];if(e.timestamp===a)return;if(e.timestamp>
a){this.I.splice(c,0,new Ob(a,b));return}}this.I.push(new Ob(a,b))}pa(){for(;2<this.I.length&&this.I[0]!==this.ca&&this.I[0]!==this.j&&this.I[0]!==this.B;)this.I.shift();const a=this.O.Fb;if(!(this.B&&this.B.timestamp>a&&this.j&&this.j.timestamp<a)){this.B=null;for(let b=0,c=this.I.length;b<c;++b){const d=this.I[b];if(d.timestamp<=a){if(!this.j||d.timestamp>this.j.timestamp)this.ca=this.j,this.j=d}else{this.B=d;break}}}}oa(a,b){if(!this.B&&!this.j)return 0;if(this.B&&!this.j)return this.B.data[b];
const c=this.O.V;let d,e,f;if(!this.B&&this.j){if(this.ca){var g=this.ca.timestamp;d=this.ca.data[b];e=this.j.timestamp;f=this.j.data[b];a>this.j.timestamp+this.O.yb&&(a=this.j.timestamp+this.O.yb);g=g===e?0:(a-g)/(e-g);return Mb(c[b].oa(),d,f,g,!0)}return this.j.data[b]}g=this.j.timestamp;d=this.j.data[b];e=this.B.timestamp;f=this.B.data[b];return Mb(c[b].oa(),d,f,g===e?0:(a-g)/(e-g),!1)}}
function L(a,b,c,d,e,f){b=new Nb(a.V.length,b,c,d,e,f);switch(c){case 0:a.ia+=8;break;case 1:a.ia+=4;break;case 2:a.ia+=2;break;case 3:a.ia+=1}a.V.push(b)}function Rb(a,b){const c=b.l,d=b.G;a.g.h()&&!a.Fa&&a.vb.push(d);a.Aa.delete(c);a.eb.delete(d);a.La.delete(d);b=a.ba.indexOf(b);-1<b&&a.ba.splice(b,1)}function Sb(a,b){(b=a.eb.get(b))&&Rb(a,b)}function Tb(a){return{roId:a.ib,sid:a.kb,netValues:a.V.map(b=>b.Da())}}
class Ub{constructor(a,b,c,d){this.g=a;this.ib=b;this.kb=c;this.G=this.g.re++;this.dd=d;this.Ib={};this.ia=0;this.yb=250;switch(this.dd){case 1:this.yb=500;break;case 2:this.yb=2500}this.V=[];this.ba=[];this.Aa=new Map;this.La=new Set;this.fb=this.xc=this.Ab=this.cb=0;this.Fa=!1;this.vb=[];this.eb=new Map;this.Fb=0;a=this.g;a.$.push(this);a.hb.set(this.ib,this);a.Ia.set(this.G,this)}ua(a){this.G=a}Pb(a,b,c){{let d=this.eb.get(b);d||(d=new Qb(this,-1,b),this.eb.set(b,d),this.ba.push(d));b=d}b.Pb(a,
c)}pa(){this.Fb=Vb(this.g);for(const a of this.ba)a.pa()}Xb(a,b){this.fb=0;for(var c of this.ba)c.sc=!1;for(let f=0,g=a.length;f<g;++f){c=a[f];var d=c.uid;var e=this.Aa.get(d);if(!e){e=d;do this.cb++,65535<this.cb&&(this.cb=0);while(this.La.has(this.cb));const h=this.cb;this.La.add(h);e=new Qb(this,e,h);this.Aa.set(d,e);this.ba.push(e)}d=e;d.sc=!0;d.Xb(c,b)}for(const f of this.ba)f.sc||Gb.push(f);for(const f of Gb)Rb(this,f);Gb.length=0}Yb(a,b,c){a.setUint16(b,this.G);b+=2;let d=0;this.Fa&&(d=1);
a.setUint8(b,d);b+=1;a.setUint16(b,this.fb);b+=2;a.setUint16(b,this.ia);b+=2;for(const e of this.ba)e.Gb&&(b=e.Yb(a,b,c));return b}Wb(a){(a=this.Aa.get(a))&&Rb(this,a)}Da(){return{hasOverriddenNids:this.Fa,netValues:this.V.map(a=>a.Da()),netInstances:this.ba.map(a=>a.Da())}}}self.Hd=Nb;self.Gd=Ob;self.Jd=Ub;"use strict";const Wb=self.Gd,Xb=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection;
function Yb(a){if(a)try{a.close()}catch(b){}}const P=[];function Zb(a){return new Promise(b=>setTimeout(b,a))}async function $b(a){if(a.Ec.length&&!(a.dc>=a.pe)){a.dc++;var b=a.Ec.shift();try{const c=await b.ze();b.resolve(c)}catch(c){b.reject(c)}a.dc--;$b(a)}}function ac(a,b){return new Promise((c,d)=>{a.Ec.push({ze:b,resolve:c,reject:d});$b(a)})}class bc{constructor(){this.pe=1;this.Ec=[];this.dc=0}}
async function cc(a,b,c){const d=dc(a,b,c.data);c=d;"o"===b&&(c=ac(a.te,()=>d));(c=await c)&&ec(a,b,c)}function Q(a,b,c){if(!a.Ma){a.Ma=!0;fc(a,b);R(a,"o",JSON.stringify({c:"disconnect",r:b,k:!!c}));var d=a.va,e=a.wa,f=a.xa,g=a.o;setTimeout(()=>{Yb(d);Yb(e);Yb(f);Yb(g)},0);a.va=null;a.wa=null;a.xa=null;a.o=null;a.Wa=!1;a.Xa=!1;a.Ya=!1;gc(a.g,a)}}
function hc(a,b,c){b.binaryType="arraybuffer";b.onopen=()=>{"o"===c?a.Wa=!0:"r"===c?a.Xa=!0:"u"===c&&(a.Ya=!0);if(!a.qa&&a.Xa&&a.Ya&&a.Wa){a.vc=performance.now();if(a.g.h()){ic(a.g,"o",JSON.stringify({c:"j",i:a.l,n:a.G,a:a.K}),0,a);var d=R,e=JSON,f=e.stringify,g=a.g.C.G,h=a.G,m=a.g.aa,z=a.g.gb,r=a.g;var O={};for(const [v,p]of r.Ia.entries()){r=p.kb;const M=[];for(var A of p.V){const S={tag:A.lb,precision:A.ra,interp:A.oa(),clientvaluetag:A.ed};"undefined"!==typeof A.Ib&&(S.userdata=A.Ib);M.push(S)}O[r]=
{nid:v,nvs:M}}A=a.g;r=[];for(const v of A.ga)r.push({tag:v.lb,precision:v.ra,interp:v.oa()});d(a,"o",f.call(e,{c:"hi",hn:g,n:h,d:m,u:z,objs:O,cvs:r,comp:jc}));for(const v of a.g.ha)!v.h()&&v!==a&&v.qa&&!v.za&&R(a,"o",JSON.stringify({c:"j",i:v.l,n:v.G,a:v.K}))}else a.oc=!0,a.h()&&kc(a,performance.now(),!0),R(a,"o",JSON.stringify({c:"comp",comp:jc}));lc(a.g,a);a.qa=!0;a.za=!1}};b.onmessage=d=>{cc(a,c,d)};b.onerror=d=>{console.error("Peer '"+a.l+"' datachannel '"+c+"' error: ",d);T(a,d);a.g.h()&&!a.h()&&
Q(a,"network error")};b.onclose=()=>{Q(a,"disconnect")}}
function mc(a){if(a!==a.g.A){var b=a.g.h();a.Wa=!1;a.Xa=!1;a.Ya=!1;a.qa=!1;a.za=!1;a.fd=performance.now();a.o=new Xb({iceServers:a.g.qc});a.o.onicecandidate=d=>{d.candidate&&U(a.g,{message:"icecandidate",toclientid:a.l,icecandidate:d.candidate})};a.o.onsignalingstatechange=()=>{a.o&&"closed"===a.o.signalingState&&Q(a,"disconnect")};a.o.oniceconnectionstatechange=()=>{a.o&&("failed"!==a.o.iceConnectionState&&"closed"!==a.o.iceConnectionState||Q(a,"disconnect"))};a.o.onconnectionstatechange=()=>{if(a.o){var d=
a.o.connectionState;"failed"!==d&&"closed"!==d||Q(a,"disconnect")}};var c=`c3mp_${a.g.lc}_${a.g.mc}_${a.g.F}`;b?(a.G=nc(a.g),a.va=a.o.createDataChannel("o",{ordered:!0,protocol:c}),hc(a,a.va,"o"),a.wa=a.o.createDataChannel("r",{ordered:!1,protocol:c}),hc(a,a.wa,"r"),a.xa=a.o.createDataChannel("u",{ordered:!1,maxRetransmits:0,protocol:c}),hc(a,a.xa,"u"),a.o.createOffer().then(d=>{a.o.setLocalDescription(d);U(a.g,{message:"offer",toclientid:a.l,offer:d})}).catch(d=>{console.error("Host error creating offer for peer '"+
a.l+"': ",d);T(a,"could not create offer for peer")})):a.o.ondatachannel=d=>{if(d.channel.protocol!==c)console.error("Unexpected datachannel protocol '"+d.channel.protocol+"', should be '"+c+"'"),T(a,"unexpected datachannel protocol '"+d.channel.protocol+"', should be '"+c+"'"),a.Ma||(Q(a,"datachannel protocol error"),l(a.g,"peer-kicked"));else{var e=d.channel.label;"o"===e?a.va=d.channel:"r"===e?a.wa=d.channel:"u"===e?a.xa=d.channel:(console.error("Unknown datachannel label: "+d.channel.label),T(a,
"unknown datachannel label '"+d.channel.label+"'"));hc(a,d.channel,e)}}}}async function oc(a,b){if(a.o)try{await a.o.addIceCandidate(b)}catch(c){console.warn("[Multiplayer] Error adding ICE candidate: ",c)}}async function R(a,b,c,d=0){pc(a.g,c);const e=qc(a,b,c,d);c=e;"o"===b&&(c=ac(a.ue,()=>e));(c=await c)&&rc(a,b,c)}
function kc(a,b,c){a.Ma||(!c&&(!a.qa||a.za)&&a.o&&25E3<b-a.fd?(console.warn("Timed out '"+a.K+"', could not establish connection after 25sec"),Q(a,"timeout")):!c&&a.qa&&!a.za&&2E4<b-a.vc?(console.warn("Timed out '"+a.K+"', not heard from for 20sec"),Q(a,"timeout")):(a.od=b,a.fc=!0,a.wc++,R(a,"u","ping:"+a.wc)))}function fc(a,b){!a.za&&a.qa&&(a.g.h()&&a!==a.g.A&&ic(a.g,"o",JSON.stringify({c:"l",i:a.l,a:a.K,r:b}),0,a),a===a.g.A||sc(a.g,a,b),a.za=!0,a.qa=!1)}
function tc(a,b){const c=jc;for(const d of b)c.includes(d)&&a.ec.push(d)}async function uc(a,b){if(0===a.ec.length)return{Jb:0,data:b};const c=new Blob([b]);if(64>c.size)return{Jb:0,data:b};a=a.ec[0];var d=new CompressionStream(a);d=c.stream().pipeThrough(d);d=await (new Response(d)).arrayBuffer();if(d.byteLength>=c.size)return{Jb:0,data:b};b=V.Qb.indexOf(a);if(0>b)throw Error("invalid compression type");return{Jb:b,data:d}}
async function qc(a,b,c,d=0){var e="string"===typeof c;const {Jb:f,data:g}=await uc(a,c);c=g;g instanceof ArrayBuffer&&(0!==f&&(d|=f<<4,e&&(d|=V.Tc)),c=new ArrayBuffer(g.byteLength+8),e=new DataView(c),e.setUint32(0,V.Vc),e.setUint32(4,d),(new Uint8Array(c,8)).set(new Uint8Array(g)));a.g.P.Oc++;d=a.g;d.P.Lb+=vc(c);d=a.g.Ic;e=a.g.Hc;a=a.g.Jc;if(0<d&&"u"===b&&Math.random()<d)return null;if(0!==e||0!==a){let h=1;"u"!==b&&Math.random()<d&&(h=3);await Zb((e+Math.random()*a)*h)}return c}
function rc(a,b,c){try{"o"===b?a.Wa&&a.va&&a.va.send(c):"r"===b?a.Xa&&a.wa&&a.wa.send(c):"u"===b&&a.Ya&&a.xa&&a.xa.send(c)}catch(d){a.Ma||(a.g.h()?"o"===b||"r"===b?("string"===typeof c?(console.error("Error sending "+c.length+"-char string on '"+b+"' to '"+a.K+"', host kicking: ",d),console.log("String that failed to send from previous error was: "+c)):console.error("Error sending "+(c.length||c.byteLength)+"-byte binary on '"+b+"' to '"+a.K+"', host kicking: ",d),Q(a,"network error")):(a.xb++,10<=
a.xb&&("string"===typeof c?(console.error("Too many errors ("+a.xb+") sending data on '"+b+"' to '"+a.K+"', kicking; last error was for sending "+c.length+"-char string: ",d),console.log("String that failed to send from previous error was: "+c)):console.error("Too many errors ("+a.xb+") sending data on '"+b+"' to '"+a.K+"', kicking; last error was for sending "+(c.length||c.byteLength)+"-byte binary: ",d),Q(a,"network error"))):console.error("Error sending data on '"+b+"': ",d))}}
function wc(a,b){if(a.fc){var c=b.indexOf(":");if(-1<c){if(parseFloat(b.substr(c+1))===a.wc){c=performance.now();a.fc=!1;var d=(c-a.od)/2;a.Bb.push(d);10<a.Bb.length&&a.Bb.shift();P.push(...a.Bb);P.sort((h,m)=>h-m);a.td=P[P.length-1]-P[0];var e=0,f=P.length;4<=P.length&&6>=P.length?(++e,--f):6<P.length&&(e+=2,f-=2);var g=0;for(let h=e;h<f;++h)g+=P[h];a.Cb=g/(f-e);P.length=0;a.g.h()||(e=b.indexOf("/"),-1<e?(b=parseFloat(b.substr(e+1)),isFinite(b)?xc(a.g,b,c,d,a.Cb):console.warn("Invalid host time from pong response")):
console.warn("Cannot parse off host time from pong response"))}}else console.warn("Cannot parse off ping ID from pong")}}async function dc(a,b,c){a.g.P.Lc++;var d=a.g;d.P.Kb+=vc(c);d=a.g.Ic;const e=a.g.Hc;a=a.g.Jc;if(0<d&&"u"===b&&Math.random()<d)return null;if(0!==e||0!==a){let f=1;"u"!==b&&Math.random()<d&&(f=3);await Zb(e*f+Math.random()*a*f)}return c instanceof ArrayBuffer?await yc(c):c}
function ec(a,b,c){if(!a.Ma)if(a.vc=performance.now(),"string"===typeof c){var d=a.g;d.P.Pa+=vc(c);if(!(""===c.trim()||4>c.length))if(d=c.substr(0,4),"ping"===d)d="pong:"+c.substr(5),a.g.h()&&(d=d+"/"+Math.round(performance.now()).toString()),R(a,"u",d);else if("pong"===d)wc(a,c);else{try{var e=JSON.parse(c)}catch(k){T(a,k);a.g.h()?(console.error("Error parsing message as JSON for peer '"+a.l+"', host kicking: ",k),Q(a,"data error")):console.error("Error parsing message as JSON for peer '"+a.l+"': ",
k);console.log("String that failed to parse from previous error: "+c);return}if(e)try{if(e.c&&"m"!==e.c){d=e;let k,C;switch(d.c){case "disconnect":d.k&&l(a.g,"peer-kicked");C=!a.g.h()&&!a.h();Q(a,d.r);C&&zc(a.g);break;case "hi":if(!a.g.h()){a.g.C.ua(d.hn);a.g.A.ua(d.n);a.g.aa=d.d;a.g.gb=d.u;var f=a.g,g=d.objs;f.Ia.clear();for(const q of f.$)if(g.hasOwnProperty(q.kb.toString())){const N=g[q.kb.toString()];q.ua(N.nid);f.Ia.set(N.nid,q);var h=N.nvs;q.V.length=0;q.ia=0;for(const B of h)L(q,B.interp,B.precision,
B.tag,B.userdata,B.clientvaluetag)}else console.warn("Could not map object SID '"+q.kb+"' - host did not send NID for it"),q.ua(-1);var m=a.g,z=d.cvs;m.tb.clear();m.ga.length=0;for(let q=0,N=z.length;q<N;++q){const B=z[q],X=new Ac(q,B.interp,B.precision,B.tag,null);m.tb.set(X.lb,X);m.ga.push(X)}m.Gc=!0;d.hasOwnProperty("comp")&&tc(a,d.comp)}break;case "comp":tc(a,d.comp);break;case "j":a.g.h()||(k=new V(a.g,d.i,d.a),k.ua(d.n),lc(a.g,k));break;case "l":!a.g.h()&&(k=a.g.W.get(d.i)||null)&&(k===k.g.A||
sc(a.g,k,d.r),Q(k,d.r));break;default:console.error("Unknown control message from peer '"+a.l+"': "+d.c),T(a,"unknown control message '"+d.c+"'")}}else{var r=a.g;d=e;const k=d.f||a.l;l(r,"peer-message",{tag:d.t,fromId:k,fromAlias:Bc(r,k),transmissionMode:b,content:d.m,contentMode:d.cm||"e"})}}catch(k){T(a,k),a.g.h()?(console.error("Error handling message for peer '"+a.l+"', host kicking: ",k),Q(a,"data error")):console.error("Error handling message for peer '"+a.l+"': ",k)}}}else{f=a.g;f.P.Pa+=vc(c.data);
!a.oc&&a.g.h()&&"u"===b&&(a.oc=!0,f=a.g,f.U&&f.h()&&U(f,{message:"confirm-peer",id:a.l}));try{var O=c.data,A=c.offset,v=c.flags;if(0===(v&V.Tb))if(d=new DataView(O,A),a.g.h()){var p=0,M=d.getFloat64(p);p+=8;M+=a.Cb;if(!(3E3<=Math.abs(M-performance.now()))){var S=d.getUint8(p);p+=1;var x=[],qa=a.g.ga;for(var J=0;J<S;++J)if(J>=qa.length)x.push(0);else{var ia=qa[J],y=void 0;switch(ia.ra){case 0:y=d.getFloat64(p);p+=8;break;case 1:y=d.getFloat32(p);p+=4;break;case 2:y=Lb(ia,d.getInt16(p));p+=2;break;
case 3:y=Lb(ia,d.getUint8(p));p+=1;break;default:y=d.getFloat32(p),p+=4}x.push(y)}a:{d=M;for(let k=0,C=a.S.length;k<C;++k){var u=a.S[k];if(u.timestamp===d)break a;if(u.timestamp>d){a.S.splice(k,0,new Wb(d,x));break a}}a.S.push(new Wb(d,x))}}}else if(0===(v&V.Sc))for(u=0,x=d.getFloat64(u),u+=8,p=d.getUint16(u),u+=2,b=0;b<p;++b){J=d.getUint16(u);u+=2;const k=d.getUint8(u);u+=1;S=null;qa=0;const C=a.g.Ia.get(J)||null;C?(S=C.V,qa=S.length,1===k&&(C.Fa=!0)):console.warn("Don't know which object corresponds to NID "+
J);const q=d.getUint16(u);u+=2;const N=d.getUint16(u);u+=2;for(M=0;M<q;++M){const B=d.getUint16(u);u+=2;if(C){ia=[];y=u;for(var ra=0;ra<qa;++ra){const X=S[ra];let ja;switch(X.ra){case 0:ja=d.getFloat64(y);y+=8;break;case 1:ja=d.getFloat32(y);y+=4;break;case 2:ja=Lb(X,d.getInt16(y));y+=2;break;case 3:ja=Lb(X,d.getUint8(y));y+=1;break;default:ja=d.getFloat32(y),y+=4}ia.push(ja)}C.Pb(x,B,ia)}u+=N}}else{x=0;ra=d.getFloat64(x);x+=8;const k=d.getUint16(x);x+=2;for(p=0;p<k;++p){const C=d.getUint16(x);x+=
2;const q=a.g.Ia.get(C)||null;q||console.warn("Don't know which object corresponds to NID "+C);const N=d.getUint16(x);x+=2;for(J=0;J<N;++J){const B=d.getUint16(x);x+=2;q&&!q.Fa&&(l(a.g,"instance-destroyed",{roId:q.ib,nid:B,timestamp:ra}),Sb(q,B))}}}else{var Pb=a.g,Nc=0===A?O:O.slice(A);const k=a.l;l(Pb,"peer-message",{fromId:k,fromAlias:Bc(Pb,k),transmissionMode:b,content:Nc,contentMode:"s"})}}catch(k){T(a,k),a.g.h()?(console.error("Error handling binary update for peer '"+a.l+"', host kicking: ",
k),Q(a,"data error")):console.error("Error handling binary update for peer '"+a.l+"': ",k)}}}
async function yc(a){if(8>a.byteLength)return console.warn(`Rejected binary message as too small (only ${a.byteLength} bytes)`),null;var b=new DataView(a),c=b.getUint32(0);b=b.getUint32(4);if(c!==V.Vc)return console.warn(`Rejected binary message with invalid magic number (0x${c.toString(16)})`),null;c=(b&V.Ld)>>4;if(0===c)return{data:a,offset:8,flags:b};if(c>=V.Qb.length)throw Error("invalid compression type");c=V.Qb[c];a=new Blob([new Uint8Array(a,8)]);c=new DecompressionStream(c);a=a.stream().pipeThrough(c);
a=await (new Response(a)).arrayBuffer();return 0===(b&V.Tc)?{data:a,offset:0,flags:b}:(new TextDecoder).decode(a)}
function Cc(a,b){b=b.kd;if(!a.B&&!a.j)return 0;if(a.B&&!a.j)return a=a.B.data,0>b||b>=a.length?0:a[b];var c=Vb(a.g);let d,e,f;if(!a.B&&a.j){if(a.ca){var g=a.ca.timestamp;d=a.ca.data[b];e=a.j.timestamp;f=a.j.data[b];c>a.j.timestamp+250&&(c=a.j.timestamp+250);g=g===e?0:(c-g)/(e-g);return Mb(a.g.ga[b].oa(),d,f,g,!0)}a=a.j.data;return 0>b||b>=a.length?0:a[b]}g=a.j.timestamp;d=a.j.data[b];e=a.B.timestamp;f=a.B.data[b];return Mb(a.g.ga[b].oa(),d,f,g===e?0:(c-g)/(e-g),!1)}
class V{constructor(a,b,c){this.g=a;this.l=b;this.G=0;this.K=c;this.va=this.o=null;this.Wa=!1;this.wa=null;this.Xa=!1;this.xa=null;this.Ya=!1;this.ue=new bc;this.te=new bc;this.oc=this.Ma=this.za=this.qa=!1;this.xb=this.fd=this.vc=0;this.ec=[];this.sd=[];this.qd=this.pd=0;this.S=[];this.B=this.j=this.ca=null;this.od=0;this.fc=!1;this.wc=1;this.Bb=[];this.td=this.Cb=0;a=this.g;a.ha.push(this);a.W.set(this.l,this);l(a,"add-peer",{id:this.l,alias:this.K})}ua(a){this.G=a}h(){return this===this.g.C}pa(a){if(0!==
this.S.length){for(;2<this.S.length&&this.S[0]!==this.ca&&this.S[0]!==this.j&&this.S[0]!==this.B;)this.S.shift();if(!(this.B&&this.B.timestamp>a&&this.j&&this.j.timestamp<a)){this.B=null;for(let b=0,c=this.S.length;b<c;++b){const d=this.S[b];if(d.timestamp<=a){if(!this.j||d.timestamp>this.j.timestamp)this.ca=this.j,this.j=d}else{this.B=d;break}}}}}}V.Vc=1664314736;V.Sc=1;V.Tc=2;V.Tb=4;V.Ld=240;V.Qb=["none","deflate","gzip"];self.Id=V;"use strict";
const Ac=self.Hd,Dc=self.Id,Ec=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,Fc=window.RTCSessionDescription||window.webkitRTCSessionDescription||window.mozRTCSessionDescription||window.msRTCSessionDescription,Gc=window.RTCIceCandidate||window.webkitRTCIceCandidate||window.mozRTCIceCandidate||window.msRTCIceCandidate,Hc=window.RTCDataChannel||window.webkitRTCDataChannel||window.mozRTCDataChannel||window.msRTCDataChannel,Ic=[{urls:"stun:stun.l.google.com:19302"}];
function Jc(a){if("undefined"===typeof CompressionStream||"function"!==typeof Blob.prototype.stream)return!1;try{return new CompressionStream(a),!0}catch(b){return!1}}function vc(a){if("number"===typeof a.byteLength)return a.byteLength;if("number"===typeof a.length)return a.length;console.warn("[Construct] Multiplayer: don't know how to measure size of data: ",a);return 0}const jc=[];Jc("deflate")&&jc.push("deflate");Jc("gzip")&&jc.push("gzip");let Kc=!1;const W=[];
function Vb(a){return a.h()?performance.now()-a.aa:performance.now()+a.J-a.M}function T(a,b){console.error(`[Multiplayer] Peer '${a.K}' (${a.l}) error: `,b)}function U(a,b){a.H&&a.la&&a.H.send(JSON.stringify(b))}function nc(a){if(a.h()){do a.Ga++,65535<a.Ga&&(a.Ga=0);while(a.Hb.has(a.Ga));var b=a.Ga;a.Hb.add(b);return b}}function ic(a,b,c,d=0,e=null){if(a.h()){var f=a.ha.slice(0);for(const g of f)g&&g!==a.A&&g!==e&&R(g,b,c,d)}}function lc(a,b){l(a,"peer-open",{id:b.l,alias:b.K})}
function sc(a,b,c){l(a,"peer-close",{id:b.l,alias:b.K,reason:c||"unknown"})}function pc(a,b){a.P.Mb+=vc(b)}function xc(a,b,c,d,e){if(!a.h()){a.na=e+a.aa;b=b+d-c;0===a.Ba.length&&(a.J=b,a.M=a.na);a.Ba.push(b);30<a.Ba.length&&a.Ba.shift();W.push(...a.Ba);W.sort((f,g)=>f-g);b=0;c=W.length;4<=W.length&&6>=W.length?(++b,--c):6<W.length&&19>=W.length?(b+=2,c-=2):19<W.length&&(b+=5,c-=5);d=0;for(e=b;e<c;++e)d+=W[e];a.da=d/(c-b);W.length=0}}
function zc(a){if(a.U){var b=Y(a.L.yd);U(a,{message:"leave"});return b}}function gc(a,b){l(a,"remove-peer",{id:b.l});a.h()&&a.h()&&a.Hb.delete(b.G);const c=a.ha.indexOf(b);-1<c&&a.ha.splice(c,1);a.W.delete(b.l);a.C===b&&(a.C=null,Lc(a,"host quit"));a.A===b&&(a.A=null,a.F="",Lc(a,"disconnect"))}function Mc(a,b){if(b)for(let c of b){"string"===typeof c&&(c={urls:c});a:{for(const d of a.qc)if(d.urls===c.urls){b=!0;break a}b=!1}b||(c.hasOwnProperty("url")||(c.url=c.urls),a.qc.push(c))}}
function Lc(a,b){if(!Kc){for(Kc=!0;a.ha.length;)Q(a.ha[0],b);Kc=!1}}
function Oc(a,b){if(a.H||a.la)return Promise.resolve();const c=Y(a.L.connect);try{a.H=new WebSocket(b,"c2multiplayer")}catch(d){return a.H=null,Z(a,d),c}a.H.onopen=()=>{-1===a.H.protocol.indexOf("c2multiplayer")?(Z(a,"server does not support 'c2multiplayer' protocol"),a.H.close(1002,"'c2multiplayer' protocol required"),a.H=null,a.la=!1):a.la=!0};a.H.onclose=()=>{l(a,"signalling-close");a.la=!1;a.U=!1;a.H=null};a.H.onerror=d=>{console.error("Signalling server error: ",d);Z(a,d)};a.H.onmessage=d=>{a:{try{var e=
JSON.parse(d.data)}catch(f){Z(a,f);break a}switch(e.message){case "welcome":d=e;1>d.protocolrev||1<d.protocolrev?(Z(a,"signalling server protocol revision not supported"),Pc(a)):(a.Cc=d.clientid,a.F="",e=a.ve,e.Fd=d.protocolrev,e.version=d.version,e.name=d.name,e.operator=d.operator,e.Bd=d.motd,Mc(a,d.ice_servers),l(a,"signalling-welcome",{myid:a.Cc,sigservinfo:{protocolrev:e.Fd,version:e.version,name:e.name,operator:e.operator,motd:e.Bd}}),Qc(a.L.connect));break;case "login-ok":a.Bc=e.alias;a.U=
!0;l(a,"signalling-login-ok",{myalias:a.Bc});Qc(a.L.login);break;case "join-ok":d=e;Lc(a,"disconnect");a.lc=d.game;a.mc=d.instance;a.F=d.room;a.A=new Dc(a,a.Cc,a.Bc);d.host?(a.C=a.A,a.Ga=0,a.Hb.clear(),a.C.ua(nc(a))):(a.Ba.length=0,a.da=0,a.J=0,a.aa=80,a.pc=30,a.gb=30,a.na=a.aa,a.M=a.aa,a.C=new Dc(a,d.hostid,d.hostalias),mc(a.C));l(a,"signalling-join-ok",{isHost:!!d.host,hostId:a.C.l,hostAlias:a.C.K,game:a.lc,gameInstance:a.mc,room:a.F});Qc(a.L.Mc);break;case "leave-ok":a.F="";l(a,"signalling-leave-ok");
Qc(a.L.yd);break;case "kicked":"host-left"===e.reason?Pc(a):(Rc(a),a.F="",l(a,"signalling-kicked"));break;case "peer-joined":d=e;a.U&&a.F&&a.h()&&((e=a.W.get(d.peerid))&&Q(e,"rejoin"),mc(new Dc(a,d.peerid,d.peeralias)));break;case "peer-quit":d=e;a.U&&a.F&&a.h()&&(e=a.W.get(d.id))&&Q(e,d.reason);break;case "icecandidate":d=e;a.U&&a.F&&(e=a.W.get(d.from))&&oc(e,new Gc(d.icecandidate));break;case "offer":Sc(a,e);break;case "answer":Tc(a,e);break;case "instance-list":l(a,"signalling-instance-list",{list:e.list});
Qc(a.L.zd);break;case "room-list":l(a,"signalling-room-list",{list:e.list});Qc(a.L.Ad);break;case "error":Z(a,e.details);break;default:Z(a,"received unknown signalling message")}}};return c}function Pc(a){a.H&&a.la&&(a.H.close(),a.H=null,a.la=!1)}function Rc(a,b){a.Ba.length=0;a.da=0;a.J=0;Lc(a,"disconnect");for(const c of a.$)c.vb.length=0,c.Aa.clear(),c.eb.clear(),c.La.clear(),c.ba.length=0;b&&zc(a)}
function Uc(a,b,c){if(!a.h()&&a.A&&a.Gc&&(b=a.tb.get(b))){b=b.kd;var d=a.A.sd;d.length<b+1&&(d.length=b+1);d[b]!==c&&(d[b]=c,a.A.pd=performance.now())}}function Y(a){a.reject&&a.reject("overlapping signalling operation");return new Promise((b,c)=>{a.resolve=b;a.reject=c})}function Qc(a){a.resolve&&a.resolve(void 0);a.resolve=null;a.reject=null}
function Z(a,b){l(a,"signalling-error",{message:b?"string"===typeof b?b:"string"===typeof b.message?b.message:"string"===typeof b.details?b.details:"string"===typeof b.data?b.data:"string"===typeof b.type?b.type:"unknown error":"unknown error"});for(const c of Object.values(a.L))c.reject&&c.reject(b),c.resolve=null,c.reject=null}
function Sc(a,b){if(a.U&&a.F&&!a.h()&&a.A&&a.C&&a.C.o&&b.from===a.C.l){var c=a.C.o;c.setRemoteDescription(new Fc(b.offer)).then(()=>{c.createAnswer().then(d=>{c.setLocalDescription(d);U(a,{message:"answer",toclientid:a.C.l,answer:d})}).catch(d=>{console.error("Peer error creating answer: ",d);T(a.A,"could not create answer to host offer")})}).catch(d=>{console.error("Peer error setting remote description: ",d);T(a.A,"could not set remote description")})}}
function Tc(a,b){a.U&&a.F&&a.h()&&(a=a.W.get(b.from))&&a.o.setRemoteDescription(new Fc(b.answer)).catch(c=>{console.error("Host error setting remote description: ",c)})}function Bc(a,b){return(a=a.W.get(b))?a.K:""}
async function Vc(a,b){if(a.h()){await Wc(a,b);const c=a.hc;let d=0,e=0;for(const f of a.$)f.vb.length&&e++;if(0!==e){c.setFloat64(d,b);d+=8;c.setUint16(d,e);d+=2;for(const f of a.$)if(b=f.vb,b.length){c.setUint16(d,f.G);d+=2;c.setUint16(d,b.length);d+=2;for(const g of b)c.setUint16(d,g),d+=2;b.length=0}ic(a,"r",a.ub.slice(0,d),Dc.Sc)}}else await Xc(a,b)}
async function Wc(a,b){const c=a.hc;let d=0,e=0;const f=await aa(a,"get-object-info",{ros:a.$.map(g=>Tb(g))});for(const g of a.$){const h=g.ib;f.hasOwnProperty(h)&&(g.Xb(f[h],b),0<g.fb&&e++)}if(0!==e){c.setFloat64(d,b);d+=8;c.setUint16(d,e);d+=2;for(const g of a.$)0<g.fb&&(d=g.Yb(c,d,b));ic(a,"u",a.ub.slice(0,d),0)}}
async function Xc(a,b){a.F&&(a.h()||0!==a.da)&&await Yc(a);if(a.A&&a.Gc){var c=a.hc,d=0,e=a.ga,f=a.A.sd,g=b-a.A.pd,h=b-a.A.qd;if(100>g||(1E3>g?95<=h:495<=h)){c.setFloat64(d,b+a.J);d+=8;c.setUint8(d,e.length);d+=1;for(let m=0,z=e.length;m<z;++m)g=e[m],h=0,m<f.length&&(h=Jb(g,f[m])),d=Kb(g,c,d,h);a.A.qd=b;R(a.C,"u",a.ub.slice(0,d))}}}async function Yc(a){const b=await aa(a,"before-client-update");for(const c of b.clientStateUpdates)Uc(a,c.tag,c.value)}
self.ea.ja(class extends self.pb{constructor(a){super(a,"multiplayer");this.qc=[];this.H=null;this.U=this.la=!1;this.ve={Fd:0,version:0,name:"",operator:"",Bd:""};this.F=this.mc=this.lc=this.Bc=this.Cc="";this.ha=[];this.W=new Map;this.Ga=0;this.Hb=new Set;this.C=this.A=null;this.aa=80;this.gb=this.pc=30;this.rd=0;this.P={ob:0,Ed:0,Oc:0,Cd:0,Dd:0,Lb:0,Mb:0,xd:0,Lc:0,vd:0,wd:0,Kb:0,Pa:0};this.ub=new ArrayBuffer(262144);this.hc=new DataView(this.ub);this.$=[];this.re=1;this.Ia=new Map;this.hb=new Map;
this.Ic=this.Jc=this.Hc=0;this.Ba=[];this.J=this.da=0;this.M=this.na=this.aa;this.ga=[];this.tb=new Map;this.Gc=!1;this.L={connect:{resolve:null,reject:null},login:{resolve:null,reject:null},Mc:{resolve:null,reject:null},yd:{resolve:null,reject:null},zd:{resolve:null,reject:null},Ad:{resolve:null,reject:null}};Mc(this,Ic);setInterval(()=>{const b=performance.now();if(this.h()){W.push(...this.ha);for(const c of W)c&&c!==this.A&&kc(c,b,!1);W.length=0}else this.C&&kc(this.C,b,!1)},2E3);window.addEventListener("unload",
()=>Lc(this,"quit"));n(this,"get-supported",()=>({isSupported:!(!Ec||!Hc)}));n(this,"add-ice-servers",b=>Mc(this,b.list));n(this,"simulate-latency",b=>{var c=b.pdv,d=b.loss;this.Hc=Math.max(b.latency,0);this.Jc=Math.max(c,0);this.Ic=Math.max(d,0)});n(this,"set-bandwidth-profile",b=>{var c=b.updateRate;b=b.delay;this.F||(this.gb=this.pc=c,this.aa=b)});n(this,"tick",b=>this.pa(b));n(this,"alert",b=>{alert(b.message)});n(this,"signalling-connect",b=>Oc(this,b.url));n(this,"signalling-disconnect",()=>
Pc(this));n(this,"signalling-login",b=>{b=b.alias;if(this.U)b=void 0;else{var c=Y(this.L.login);U(this,{message:"login",protocolrev:1,datachannelrev:2,compressionformats:jc,alias:b});b=c}return b});n(this,"signalling-join-room",b=>{var c=b.game;var d=b.instance,e=b.room;b=b.maxClients;if(this.U&&!this.F){var f=Y(this.L.Mc);U(this,{message:"join",game:c,instance:d,room:e,max_clients:b});c=f}else c=void 0;return c});n(this,"signalling-auto-join-room",b=>{var c=b.game;var d=b.instance,e=b.room,f=b.maxClients;
b=b.lock;if(this.U&&!this.F){var g=Y(this.L.Mc);U(this,{message:"auto-join",game:c,instance:d,room:e,max_clients:f,lock_when_full:b});c=g}else c=void 0;return c});n(this,"signalling-leave-room",()=>zc(this));n(this,"signalling-list-game-instances",b=>{b=b.game;if(this.H&&this.la){var c=Y(this.L.zd);U(this,{message:"list-instances",game:b});b=c}else b=void 0;return b});n(this,"signalling-list-rooms",b=>{var c=b.game;var d=b.instance;b=b.which;if(this.H&&this.la){var e=Y(this.L.Ad);U(this,{message:"list-rooms",
game:c,instance:d,which:b});c=e}else c=void 0;return c});n(this,"disconnect-room",()=>Rc(this,!0));n(this,"peer-send-message",b=>{const c=b.tag;var d=b.message;const e=b.transmissionMode,f=b.contentMode;if(b=this.W.get(b.id)||null)"s"===f&&d instanceof ArrayBuffer?R(b,e,d,Dc.Tb):(d={c:"m",cm:f,m:d},"e"===f&&(d.t=c),R(b,e,JSON.stringify(d)))});n(this,"host-broadcast",b=>{var c=b.fromId;const d=b.tag,e=b.message,f=b.transmissionMode;b=b.contentMode;const g=this.W.get(c)||null;"s"===b&&e instanceof ArrayBuffer?
ic(this,f,e,Dc.Tb,g):(c={c:"m",cm:b,f:c,m:e},"e"===b&&(c.t=d),ic(this,f,JSON.stringify(c),0,g))});n(this,"kick-peer",b=>{if(this.h()){var c=b.reason;(b=this.W.get(b.id)||null)&&Q(b,c,!0)}});n(this,"sync-object",b=>{const c=b.data,d=b.precision,e=b.bandwidth;for(const f of b.objectClasses)b=new self.Jd(this,f.roId,f.sid,e),1===c?(L(b,1,d,"x"),L(b,1,d,"y")):2===c?L(b,2,d,"a"):3===c&&(L(b,1,d,"x"),L(b,1,d,"y"),L(b,2,d,"a"))});n(this,"sync-inst-var",b=>{const c=b.precision,d=b.interp,e=b.cvt;for(const f of b.syncData)L(this.hb.get(f.roId),
d,c,"iv",f.varIndex,e)});n(this,"associate-object",b=>{var c=b.peerId;const d=b.instUid;b=this.hb.get(b.roId);c=this.W.get(c);if(b&&c&&this.h())if(c=c.G,b.Aa.has(d))console.warn("OverrideNid passed id "+d+" which is already in use and cannot be overridden");else if(b.La.has(c))console.warn("OverrideNid passed nid "+c+" which is already in use and cannot be overridden");else{var e=new Qb(b,d,c);b.Aa.set(d,e);b.La.add(c);b.ba.push(e);b.Fa=!0}});n(this,"remove-object-id",b=>this.Wb(b.uid));n(this,"remove-net-insts",
b=>{for(const [c,d]of Object.entries(b))if(b=this.hb.get(parseInt(c,10)))for(const e of d)Sb(b,e)});n(this,"remove-object-nid",b=>{const c=b.nid;(b=this.hb.get(b.roId))&&Sb(b,c)});n(this,"set-client-state",b=>Uc(this,b.tag,b.value));n(this,"add-client-input-value",b=>{var c=b.tag;b=new Ac(this.ga.length,b.interp,b.precision,c,null);this.tb.set(c,b);this.ga.push(b)})}h(){return!!this.F&&this.A&&this.C===this.A}pa(a){if(!this.F)return null;a=a.dt;var b=performance.now();b-this.rd>=1E3/(this.h()?this.pc:
this.gb)-5&&(Vc(this,b),this.rd=b);var c=this.P;1E3<=b-c.ob&&(c.Ed=c.Oc,c.Cd=c.Lb,c.Dd=c.Mb,c.xd=c.Lc,c.vd=c.Kb,c.wd=c.Pa,c.Oc=0,c.Lb=0,c.Mb=0,c.Lc=0,c.Kb=0,c.Pa=0,c.ob+=1E3,500<b-c.ob&&(c.ob=b),l(this,"stats",{stats:{outboundPerSec:c.Ed,outboundBandwidthPerSec:c.Cd,outboundDecompressedBandwidthPerSec:c.Dd,inboundPerSec:c.xd,inboundBandwidthPerSec:c.vd,inboundDecompressedBandwidthPerSec:c.wd}}));this.h()||(this.J<this.da?(this.J+=10*a,this.J>this.da&&(this.J=this.da)):this.J>this.da&&(this.J-=10*
a,this.J<this.da&&(this.J=this.da)),this.M<this.na?(this.M+=30*a,this.M>this.na&&(this.M=this.na)):this.M>this.na&&(this.M-=30*a,this.M<this.na&&(this.M=this.na)));a=Vb(this);for(var d of this.ha)d.pa(a);for(var e of this.$)e.pa();d=Vb(this);e=this.h()?performance.now():performance.now()+this.J+this.M;a=this.aa;b={};for(var f of this.ha){c={};for(const g of this.ga)c[g.lb]=Cc(f,g);b[f.l]={nid:f.G,latency:f.Cb,pdv:f.td,clientState:c}}f={};for(const g of this.$)f[g.ib]=g.Da();return{simulationTime:d,
hostInputArrivalTime:e,clientDelay:a,peerData:b,roData:f,isReadyForInput:this.F?this.h()?!0:0!==this.da:!1}}Wb(a){for(const b of this.$)b.Wb(a)}});"use strict";function Zc(a){a.stopPropagation()}
self.ea.ja(class extends self.Ca{constructor(a){super(a,"progress-bar")}ta(a,b){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Zc);c.addEventListener("pointermove",Zc);c.addEventListener("pointerrawupdate",Zc);c.addEventListener("pointerup",Zc);c.addEventListener("mousedown",Zc);c.addEventListener("mouseup",Zc);c.addEventListener("click",()=>D(this,"click",a));b.id&&(c.id=b.id);b.className&&
(c.className=b.className);this.R(c,b);return c}R(a,b){a.title=b.title;const c=b.value;b=b.max;0<b&&0<=c?(a.max=b,a.value=c):(a.removeAttribute("value"),a.removeAttribute("max"))}});
